namespace DownTrack.Infrastructure.Localization;

internal static class CompleteUiTranslationCatalog
{
    private static readonly string[] Keys =
    [
        "App.Settings","Shell.AddMedia","Shell.AddFolder","Shell.Home","Shell.Forward","Shell.Back","Shell.Library","Shell.Rename","Shell.Delete","Shell.Cancel",
        "Shell.RootFolders","Library.Overline","Library.Title","Library.Subtitle","Library.Folder","Library.Location","Library.Action","Library.Open","Library.EmptyTitle","Library.EmptySubtitle",
        "Explorer.Overline","Explorer.Name","Explorer.Type","Explorer.State","Explorer.EmptyTitle","Explorer.EmptySubtitle","Pending.Title","Pending.Subtitle",
        "AddMedia.Title","AddMedia.Subtitle","AddMedia.UrlHint","AddMedia.Analyze","AddMedia.SelectAll","AddMedia.Mp3All","AddMedia.Format","AddMedia.AudioQuality","AddMedia.VideoQuality","AddMedia.NoMedia","AddMedia.NoMediaSubtitle","AddMedia.Preparing","AddMedia.PreparingSubtitle","AddMedia.Destination","AddMedia.Stage","AddMedia.Cancel",
        "Settings.Title","Settings.Subtitle","Settings.Appearance","Settings.AppearanceSubtitle","Settings.Language","Settings.LanguageDescription","Settings.Automatic","Settings.ThemeLight","Settings.ThemeDark","Settings.ThemeSystem","Settings.Updates","Settings.UpdatesSubtitle","Settings.AppUpdates","Settings.Check","Settings.Update","Settings.ToolUpdates","Settings.AutoUpdate","Settings.AutoToolUpdate","Settings.Defaults","Settings.DefaultsSubtitle","Settings.DefaultFormat","Settings.DefaultAudioQuality","Settings.DefaultVideoQuality","Settings.Cancel","Settings.Save"
    ];

    public static void Apply(IDictionary<string, Dictionary<string,string>> dictionaries)
    {
        foreach (var pack in Packs)
        {
            if (!dictionaries.TryGetValue(pack.Key, out var dictionary))
                continue;

            foreach (var (key, value) in pack.Value)
                dictionary[key] = value;
        }
    }

    private static readonly IReadOnlyDictionary<string, Dictionary<string,string>> Packs =
        new Dictionary<string, Dictionary<string,string>>
        {
            ["nl"] = Pack(
                ("App.Settings","Instellingen"),("Shell.AddMedia","Media toevoegen"),("Shell.AddFolder","Map toevoegen"),("Shell.Home","Start"),("Shell.Forward","Vooruit"),("Shell.Back","Terug"),("Shell.Library","Bibliotheek"),("Shell.Rename","Hernoemen"),("Shell.Delete","Verwijderen"),("Shell.Cancel","Annuleren"),("Shell.RootFolders","Hoofdmappen"),
                ("Library.Overline","MIJN BIBLIOTHEEK"),("Library.Title","Je bibliotheek"),("Library.Subtitle","Je mappen, jouw indeling, één rustige werkplek."),("Library.Folder","MAP"),("Library.Location","LOCATIE"),("Library.Action","ACTIE"),("Library.Open","Openen"),("Library.EmptyTitle","Je bibliotheek wacht op je eerste map"),("Library.EmptySubtitle","Kies een map die DownTrack mag beheren. Niets verandert op schijf totdat je opslaat."),
                ("Explorer.Overline","BIBLIOTHEEK / VERKENNER"),("Explorer.Name","NAAM"),("Explorer.Type","TYPE"),("Explorer.State","STATUS"),("Explorer.EmptyTitle","Deze map is leeg"),("Explorer.EmptySubtitle","Maak een map of voeg media toe. Nieuwe wijzigingen verschijnen hier direct."),("Pending.Title","Wachtende wijzigingen"),("Pending.Subtitle","Controleer alles voordat er naar de schijf wordt geschreven."),
                ("AddMedia.Title","Media toevoegen"),("AddMedia.Subtitle","Plak een video of playlist, controleer elk item en voeg alleen toe wat je wilt."),("AddMedia.UrlHint","Plak een YouTube-video- of playlist-URL"),("AddMedia.Analyze","Analyseren"),("AddMedia.SelectAll","Alles selecteren"),("AddMedia.Mp3All","MP3 voor alles"),("AddMedia.Format","FORMAAT"),("AddMedia.AudioQuality","AUDIOKWALITEIT"),("AddMedia.VideoQuality","VIDEOKWALITEIT"),("AddMedia.NoMedia","Plak een YouTube-link"),("AddMedia.NoMediaSubtitle","Tijdens het analyseren wordt niets gedownload. Geselecteerde items worden wachtende wijzigingen."),("AddMedia.Preparing","Media voorbereiden…"),("AddMedia.PreparingSubtitle","Media-engine controleren en link analyseren."),("AddMedia.Destination","BESTEMMING"),("AddMedia.Stage","Aan downloads toevoegen"),("AddMedia.Cancel","Annuleren"),
                ("Settings.Title","Instellingen"),("Settings.Subtitle","Stel DownTrack precies in zoals jij het wilt."),("Settings.Appearance","Weergave"),("Settings.AppearanceSubtitle","Kies hoe DownTrack het Windows-thema volgt."),("Settings.Language","Taal"),("Settings.LanguageDescription","Gebruik Automatisch voor de Windows-weergavetaal of kies handmatig."),("Settings.Automatic","Automatisch (Windows)"),("Settings.ThemeLight","Licht"),("Settings.ThemeDark","Donker"),("Settings.ThemeSystem","Systeem"),("Settings.Updates","Updates"),("Settings.UpdatesSubtitle","Houd DownTrack en de mediahulpmiddelen actueel."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Controleren"),("Settings.Update","Bijwerken"),("Settings.ToolUpdates","Mediahulpmiddelen"),("Settings.AutoUpdate","Automatisch controleren op DownTrack-updates"),("Settings.AutoToolUpdate","Mediahulpmiddelen automatisch bijwerken"),("Settings.Defaults","Downloadstandaarden"),("Settings.DefaultsSubtitle","Deze waarden worden gebruikt bij het analyseren van nieuwe media."),("Settings.DefaultFormat","Standaardformaat"),("Settings.DefaultAudioQuality","Standaard audiokwaliteit"),("Settings.DefaultVideoQuality","Standaard videokwaliteit"),("Settings.Cancel","Annuleren"),("Settings.Save","Instellingen opslaan")
            ),
            ["pl"] = Pack(
                ("App.Settings","Ustawienia"),("Shell.AddMedia","Dodaj multimedia"),("Shell.AddFolder","Dodaj folder"),("Shell.Home","Start"),("Shell.Forward","Dalej"),("Shell.Back","Wstecz"),("Shell.Library","Biblioteka"),("Shell.Rename","Zmień nazwę"),("Shell.Delete","Usuń"),("Shell.Cancel","Anuluj"),("Shell.RootFolders","Foldery główne"),
                ("Library.Overline","MOJA BIBLIOTEKA"),("Library.Title","Twoja biblioteka"),("Library.Subtitle","Twoje foldery, Twój układ, spokojne miejsce pracy."),("Library.Folder","FOLDER"),("Library.Location","LOKALIZACJA"),("Library.Action","AKCJA"),("Library.Open","Otwórz"),("Library.EmptyTitle","Twoja biblioteka czeka na pierwszy folder"),("Library.EmptySubtitle","Wybierz folder zarządzany przez DownTrack. Nic na dysku nie zmieni się, dopóki nie zapiszesz."),
                ("Explorer.Overline","BIBLIOTEKA / EKSPLORATOR"),("Explorer.Name","NAZWA"),("Explorer.Type","TYP"),("Explorer.State","STAN"),("Explorer.EmptyTitle","Ten folder jest pusty"),("Explorer.EmptySubtitle","Utwórz folder lub dodaj multimedia. Nowe oczekujące elementy pojawią się tutaj od razu."),("Pending.Title","Oczekujące zmiany"),("Pending.Subtitle","Sprawdź wszystko przed zapisaniem na dysku."),
                ("AddMedia.Title","Dodaj multimedia"),("AddMedia.Subtitle","Wklej film lub playlistę, sprawdź każdy element i dodaj tylko to, czego potrzebujesz."),("AddMedia.UrlHint","Wklej adres filmu lub playlisty YouTube"),("AddMedia.Analyze","Analizuj"),("AddMedia.SelectAll","Zaznacz wszystko"),("AddMedia.Mp3All","MP3 dla wszystkich"),("AddMedia.Format","FORMAT"),("AddMedia.AudioQuality","JAKOŚĆ AUDIO"),("AddMedia.VideoQuality","JAKOŚĆ WIDEO"),("AddMedia.NoMedia","Wklej link YouTube"),("AddMedia.NoMediaSubtitle","Podczas analizy nic nie jest pobierane. Wybrane elementy trafiają do oczekujących zmian."),("AddMedia.Preparing","Przygotowywanie multimediów…"),("AddMedia.PreparingSubtitle","Sprawdzanie silnika multimediów i analiza linku."),("AddMedia.Destination","MIEJSCE DOCELOWE"),("AddMedia.Stage","Dodaj do pobrań"),("AddMedia.Cancel","Anuluj"),
                ("Settings.Title","Ustawienia"),("Settings.Subtitle","Dostosuj DownTrack dokładnie do swoich potrzeb."),("Settings.Appearance","Wygląd"),("Settings.AppearanceSubtitle","Wybierz, jak DownTrack ma podążać za motywem Windows."),("Settings.Language","Język"),("Settings.LanguageDescription","Wybierz Automatycznie, aby użyć języka Windows, albo wybierz go ręcznie."),("Settings.Automatic","Automatycznie (Windows)"),("Settings.ThemeLight","Jasny"),("Settings.ThemeDark","Ciemny"),("Settings.ThemeSystem","Systemowy"),("Settings.Updates","Aktualizacje"),("Settings.UpdatesSubtitle","Dbaj o aktualność aplikacji i narzędzi multimedialnych."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Sprawdź"),("Settings.Update","Aktualizuj"),("Settings.ToolUpdates","Narzędzia multimedialne"),("Settings.AutoUpdate","Automatycznie sprawdzaj aktualizacje DownTrack"),("Settings.AutoToolUpdate","Automatycznie aktualizuj narzędzia multimedialne"),("Settings.Defaults","Domyślne pobieranie"),("Settings.DefaultsSubtitle","Te wartości są używane podczas analizy nowych multimediów."),("Settings.DefaultFormat","Format domyślny"),("Settings.DefaultAudioQuality","Domyślna jakość audio"),("Settings.DefaultVideoQuality","Domyślna jakość wideo"),("Settings.Cancel","Anuluj"),("Settings.Save","Zapisz ustawienia")
            ),
            ["cs"] = Pack(
                ("App.Settings","Nastavení"),("Shell.AddMedia","Přidat média"),("Shell.AddFolder","Přidat složku"),("Shell.Home","Domů"),("Shell.Forward","Vpřed"),("Shell.Back","Zpět"),("Shell.Library","Knihovna"),("Shell.Rename","Přejmenovat"),("Shell.Delete","Smazat"),("Shell.Cancel","Zrušit"),("Shell.RootFolders","Kořenové složky"),
                ("Library.Overline","MOJE KNIHOVNA"),("Library.Title","Vaše knihovna"),("Library.Subtitle","Vaše složky, vaše uspořádání, klidný pracovní prostor."),("Library.Folder","SLOŽKA"),("Library.Location","UMÍSTĚNÍ"),("Library.Action","AKCE"),("Library.Open","Otevřít"),("Library.EmptyTitle","Vaše knihovna čeká na první složku"),("Library.EmptySubtitle","Vyberte složku, kterou má DownTrack spravovat. Na disku se nic nezmění, dokud neuložíte."),
                ("Explorer.Overline","KNIHOVNA / PRŮZKUMNÍK"),("Explorer.Name","NÁZEV"),("Explorer.Type","TYP"),("Explorer.State","STAV"),("Explorer.EmptyTitle","Tato složka je prázdná"),("Explorer.EmptySubtitle","Vytvořte složku nebo přidejte média. Nové čekající položky se zde objeví ihned."),("Pending.Title","Nevyřízené změny"),("Pending.Subtitle","Před zápisem na disk vše zkontrolujte."),
                ("AddMedia.Title","Přidat média"),("AddMedia.Subtitle","Vložte video nebo playlist, zkontrolujte každou položku a přidejte jen to, co chcete."),("AddMedia.UrlHint","Vložte adresu videa nebo playlistu YouTube"),("AddMedia.Analyze","Analyzovat"),("AddMedia.SelectAll","Vybrat vše"),("AddMedia.Mp3All","MP3 pro všechny"),("AddMedia.Format","FORMÁT"),("AddMedia.AudioQuality","KVALITA ZVUKU"),("AddMedia.VideoQuality","KVALITA VIDEA"),("AddMedia.NoMedia","Vložte odkaz YouTube"),("AddMedia.NoMediaSubtitle","Během analýzy se nic nestahuje. Vybrané položky se stanou nevyřízenými změnami."),("AddMedia.Preparing","Příprava médií…"),("AddMedia.PreparingSubtitle","Kontrola mediálního enginu a analýza odkazu."),("AddMedia.Destination","CÍL"),("AddMedia.Stage","Přidat ke stažení"),("AddMedia.Cancel","Zrušit"),
                ("Settings.Title","Nastavení"),("Settings.Subtitle","Nastavte DownTrack přesně podle sebe."),("Settings.Appearance","Vzhled"),("Settings.AppearanceSubtitle","Zvolte, jak má DownTrack sledovat motiv Windows."),("Settings.Language","Jazyk"),("Settings.LanguageDescription","Použijte Automaticky pro jazyk Windows nebo vyberte jazyk ručně."),("Settings.Automatic","Automaticky (Windows)"),("Settings.ThemeLight","Světlý"),("Settings.ThemeDark","Tmavý"),("Settings.ThemeSystem","Systém"),("Settings.Updates","Aktualizace"),("Settings.UpdatesSubtitle","Udržujte aplikaci a mediální nástroje aktuální."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Zkontrolovat"),("Settings.Update","Aktualizovat"),("Settings.ToolUpdates","Mediální nástroje"),("Settings.AutoUpdate","Automaticky kontrolovat aktualizace DownTrack"),("Settings.AutoToolUpdate","Automaticky aktualizovat mediální nástroje"),("Settings.Defaults","Výchozí nastavení stahování"),("Settings.DefaultsSubtitle","Tyto hodnoty se použijí při analýze nových médií."),("Settings.DefaultFormat","Výchozí formát"),("Settings.DefaultAudioQuality","Výchozí kvalita zvuku"),("Settings.DefaultVideoQuality","Výchozí kvalita videa"),("Settings.Cancel","Zrušit"),("Settings.Save","Uložit nastavení")
            ),
            ["tr"] = Pack(
                ("App.Settings","Ayarlar"),("Shell.AddMedia","Medya ekle"),("Shell.AddFolder","Klasör ekle"),("Shell.Home","Ana sayfa"),("Shell.Forward","İleri"),("Shell.Back","Geri"),("Shell.Library","Kitaplık"),("Shell.Rename","Yeniden adlandır"),("Shell.Delete","Sil"),("Shell.Cancel","İptal"),("Shell.RootFolders","Kök klasörler"),
                ("Library.Overline","KÜTÜPHANEM"),("Library.Title","Kitaplığınız"),("Library.Subtitle","Klasörleriniz, düzeniniz, sakin bir çalışma alanı."),("Library.Folder","KLASÖR"),("Library.Location","KONUM"),("Library.Action","İŞLEM"),("Library.Open","Aç"),("Library.EmptyTitle","Kitaplığınız ilk klasörünü bekliyor"),("Library.EmptySubtitle","DownTrack'in yöneteceği bir klasör seçin. Kaydedene kadar diskte hiçbir şey değişmez."),
                ("Explorer.Overline","KİTAPLIK / DOSYA GEZGİNİ"),("Explorer.Name","AD"),("Explorer.Type","TÜR"),("Explorer.State","DURUM"),("Explorer.EmptyTitle","Bu klasör boş"),("Explorer.EmptySubtitle","Klasör oluşturun veya medya ekleyin. Bekleyen yeni öğeler hemen burada görünür."),("Pending.Title","Bekleyen değişiklikler"),("Pending.Subtitle","Diske yazmadan önce her şeyi gözden geçirin."),
                ("AddMedia.Title","Medya ekle"),("AddMedia.Subtitle","Bir video veya oynatma listesi yapıştırın, her öğeyi inceleyin ve yalnızca istediklerinizi ekleyin."),("AddMedia.UrlHint","YouTube video veya oynatma listesi URL'sini yapıştırın"),("AddMedia.Analyze","Analiz et"),("AddMedia.SelectAll","Tümünü seç"),("AddMedia.Mp3All","Tümüne MP3"),("AddMedia.Format","FORMAT"),("AddMedia.AudioQuality","SES KALİTESİ"),("AddMedia.VideoQuality","VİDEO KALİTESİ"),("AddMedia.NoMedia","YouTube bağlantısı yapıştırın"),("AddMedia.NoMediaSubtitle","Analiz sırasında hiçbir şey indirilmez. Seçilen öğeler bekleyen değişikliklere dönüşür."),("AddMedia.Preparing","Medya hazırlanıyor…"),("AddMedia.PreparingSubtitle","Medya motoru kontrol ediliyor ve bağlantı analiz ediliyor."),("AddMedia.Destination","HEDEF"),("AddMedia.Stage","İndirmelere ekle"),("AddMedia.Cancel","İptal"),
                ("Settings.Title","Ayarlar"),("Settings.Subtitle","DownTrack'i tam istediğiniz gibi özelleştirin."),("Settings.Appearance","Görünüm"),("Settings.AppearanceSubtitle","DownTrack'in Windows temasını nasıl izleyeceğini seçin."),("Settings.Language","Dil"),("Settings.LanguageDescription","Windows görüntüleme dilini kullanmak için Otomatik'i seçin veya manuel olarak seçin."),("Settings.Automatic","Otomatik (Windows)"),("Settings.ThemeLight","Açık"),("Settings.ThemeDark","Koyu"),("Settings.ThemeSystem","Sistem"),("Settings.Updates","Güncellemeler"),("Settings.UpdatesSubtitle","Uygulamayı ve medya araçlarını güncel tutun."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Kontrol et"),("Settings.Update","Güncelle"),("Settings.ToolUpdates","Medya araçları"),("Settings.AutoUpdate","DownTrack güncellemelerini otomatik kontrol et"),("Settings.AutoToolUpdate","Medya araçlarını otomatik güncel tut"),("Settings.Defaults","İndirme varsayılanları"),("Settings.DefaultsSubtitle","Bu değerler yeni medya analiz edilirken kullanılır."),("Settings.DefaultFormat","Varsayılan biçim"),("Settings.DefaultAudioQuality","Varsayılan ses kalitesi"),("Settings.DefaultVideoQuality","Varsayılan video kalitesi"),("Settings.Cancel","İptal"),("Settings.Save","Ayarları kaydet")
            ),
            ["uk"] = Pack(
                ("App.Settings","Налаштування"),("Shell.AddMedia","Додати медіа"),("Shell.AddFolder","Додати папку"),("Shell.Home","Головна"),("Shell.Forward","Вперед"),("Shell.Back","Назад"),("Shell.Library","Бібліотека"),("Shell.Rename","Перейменувати"),("Shell.Delete","Видалити"),("Shell.Cancel","Скасувати"),("Shell.RootFolders","Кореневі папки"),
                ("Library.Overline","МОЯ БІБЛІОТЕКА"),("Library.Title","Ваша бібліотека"),("Library.Subtitle","Ваші папки, ваша організація, спокійний робочий простір."),("Library.Folder","ПАПКА"),("Library.Location","РОЗТАШУВАННЯ"),("Library.Action","ДІЯ"),("Library.Open","Відкрити"),("Library.EmptyTitle","Ваша бібліотека чекає на першу папку"),("Library.EmptySubtitle","Виберіть папку, якою керуватиме DownTrack. На диску нічого не зміниться, доки ви не збережете."),
                ("Explorer.Overline","БІБЛІОТЕКА / ПРОВІДНИК"),("Explorer.Name","НАЗВА"),("Explorer.Type","ТИП"),("Explorer.State","СТАН"),("Explorer.EmptyTitle","Ця папка порожня"),("Explorer.EmptySubtitle","Створіть папку або додайте медіа. Нові очікувані елементи з'являться тут одразу."),("Pending.Title","Очікувані зміни"),("Pending.Subtitle","Перевірте все перед записом на диск."),
                ("AddMedia.Title","Додати медіа"),("AddMedia.Subtitle","Вставте відео або плейлист, перевірте кожен елемент і додайте лише потрібне."),("AddMedia.UrlHint","Вставте URL відео або плейлиста YouTube"),("AddMedia.Analyze","Аналізувати"),("AddMedia.SelectAll","Вибрати все"),("AddMedia.Mp3All","MP3 для всіх"),("AddMedia.Format","ФОРМАТ"),("AddMedia.AudioQuality","ЯКІСТЬ АУДІО"),("AddMedia.VideoQuality","ЯКІСТЬ ВІДЕО"),("AddMedia.NoMedia","Вставте посилання YouTube"),("AddMedia.NoMediaSubtitle","Під час аналізу нічого не завантажується. Вибрані елементи стають очікуваними змінами."),("AddMedia.Preparing","Підготовка медіа…"),("AddMedia.PreparingSubtitle","Перевірка медіадвигуна та аналіз посилання."),("AddMedia.Destination","ПРИЗНАЧЕННЯ"),("AddMedia.Stage","Додати до завантажень"),("AddMedia.Cancel","Скасувати"),
                ("Settings.Title","Налаштування"),("Settings.Subtitle","Налаштуйте DownTrack так, як вам зручно."),("Settings.Appearance","Вигляд"),("Settings.AppearanceSubtitle","Виберіть, як DownTrack слідкує за темою Windows."),("Settings.Language","Мова"),("Settings.LanguageDescription","Використовуйте Автоматично для мови Windows або виберіть мову вручну."),("Settings.Automatic","Автоматично (Windows)"),("Settings.ThemeLight","Світла"),("Settings.ThemeDark","Темна"),("Settings.ThemeSystem","Системна"),("Settings.Updates","Оновлення"),("Settings.UpdatesSubtitle","Підтримуйте застосунок і медіаінструменти в актуальному стані."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Перевірити"),("Settings.Update","Оновити"),("Settings.ToolUpdates","Медіаінструменти"),("Settings.AutoUpdate","Автоматично перевіряти оновлення DownTrack"),("Settings.AutoToolUpdate","Автоматично оновлювати медіаінструменти"),("Settings.Defaults","Типові параметри завантаження"),("Settings.DefaultsSubtitle","Ці значення використовуються під час аналізу нового медіа."),("Settings.DefaultFormat","Типовий формат"),("Settings.DefaultAudioQuality","Типова якість аудіо"),("Settings.DefaultVideoQuality","Типова якість відео"),("Settings.Cancel","Скасувати"),("Settings.Save","Зберегти налаштування")
            ),
            ["ru"] = Pack(
                ("App.Settings","Настройки"),("Shell.AddMedia","Добавить медиа"),("Shell.AddFolder","Добавить папку"),("Shell.Home","Главная"),("Shell.Forward","Вперёд"),("Shell.Back","Назад"),("Shell.Library","Библиотека"),("Shell.Rename","Переименовать"),("Shell.Delete","Удалить"),("Shell.Cancel","Отмена"),("Shell.RootFolders","Корневые папки"),
                ("Library.Overline","МОЯ БИБЛИОТЕКА"),("Library.Title","Ваша библиотека"),("Library.Subtitle","Ваши папки, ваш порядок, спокойное рабочее пространство."),("Library.Folder","ПАПКА"),("Library.Location","РАСПОЛОЖЕНИЕ"),("Library.Action","ДЕЙСТВИЕ"),("Library.Open","Открыть"),("Library.EmptyTitle","Ваша библиотека ждёт первую папку"),("Library.EmptySubtitle","Выберите папку для управления в DownTrack. До сохранения ничего на диске не изменяется."),
                ("Explorer.Overline","БИБЛИОТЕКА / ПРОВОДНИК"),("Explorer.Name","ИМЯ"),("Explorer.Type","ТИП"),("Explorer.State","СОСТОЯНИЕ"),("Explorer.EmptyTitle","Папка пуста"),("Explorer.EmptySubtitle","Создайте папку или добавьте медиа. Новые ожидающие элементы появятся здесь сразу."),("Pending.Title","Ожидающие изменения"),("Pending.Subtitle","Проверьте всё перед записью на диск."),
                ("AddMedia.Title","Добавить медиа"),("AddMedia.Subtitle","Вставьте видео или плейлист, проверьте каждый элемент и добавьте только нужное."),("AddMedia.UrlHint","Вставьте URL видео или плейлиста YouTube"),("AddMedia.Analyze","Анализировать"),("AddMedia.SelectAll","Выбрать всё"),("AddMedia.Mp3All","MP3 для всех"),("AddMedia.Format","ФОРМАТ"),("AddMedia.AudioQuality","КАЧЕСТВО АУДИО"),("AddMedia.VideoQuality","КАЧЕСТВО ВИДЕО"),("AddMedia.NoMedia","Вставьте ссылку YouTube"),("AddMedia.NoMediaSubtitle","Во время анализа ничего не скачивается. Выбранные элементы становятся ожидающими изменениями."),("AddMedia.Preparing","Подготовка медиа…"),("AddMedia.PreparingSubtitle","Проверка медиадвижка и анализ ссылки."),("AddMedia.Destination","НАЗНАЧЕНИЕ"),("AddMedia.Stage","Добавить в загрузки"),("AddMedia.Cancel","Отмена"),
                ("Settings.Title","Настройки"),("Settings.Subtitle","Настройте DownTrack так, как вам удобно."),("Settings.Appearance","Оформление"),("Settings.AppearanceSubtitle","Выберите, как DownTrack должен следовать теме Windows."),("Settings.Language","Язык"),("Settings.LanguageDescription","Используйте Автоматически для языка Windows или выберите язык вручную."),("Settings.Automatic","Автоматически (Windows)"),("Settings.ThemeLight","Светлая"),("Settings.ThemeDark","Тёмная"),("Settings.ThemeSystem","Системная"),("Settings.Updates","Обновления"),("Settings.UpdatesSubtitle","Поддерживайте приложение и медиаинструменты в актуальном состоянии."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Проверить"),("Settings.Update","Обновить"),("Settings.ToolUpdates","Медиаинструменты"),("Settings.AutoUpdate","Автоматически проверять обновления DownTrack"),("Settings.AutoToolUpdate","Автоматически обновлять меди-инструменты"),("Settings.Defaults","Настройки загрузки по умолчанию"),("Settings.DefaultsSubtitle","Эти значения используются при анализе новых медиа."),("Settings.DefaultFormat","Формат по умолчанию"),("Settings.DefaultAudioQuality","Качество аудио по умолчанию"),("Settings.DefaultVideoQuality","Качество видео по умолчанию"),("Settings.Cancel","Отмена"),("Settings.Save","Сохранить настройки")
            ),
            ["ar"] = Pack(
                ("App.Settings","الإعدادات"),("Shell.AddMedia","إضافة وسائط"),("Shell.AddFolder","إضافة مجلد"),("Shell.Home","الرئيسية"),("Shell.Forward","التالي"),("Shell.Back","رجوع"),("Shell.Library","المكتبة"),("Shell.Rename","إعادة تسمية"),("Shell.Delete","حذف"),("Shell.Cancel","إلغاء"),("Shell.RootFolders","المجلدات الرئيسية"),
                ("Library.Overline","مكتبتي"),("Library.Title","مكتبتك"),("Library.Subtitle","مجلداتك، تنظيمك، ومساحة عمل هادئة."),("Library.Folder","مجلد"),("Library.Location","الموقع"),("Library.Action","الإجراء"),("Library.Open","فتح"),("Library.EmptyTitle","مكتبتك بانتظار مجلدها الأول"),("Library.EmptySubtitle","اختر مجلدًا يديره DownTrack. لن يتغير شيء على القرص حتى تحفظ."),
                ("Explorer.Overline","المكتبة / المستكشف"),("Explorer.Name","الاسم"),("Explorer.Type","النوع"),("Explorer.State","الحالة"),("Explorer.EmptyTitle","هذا المجلد فارغ"),("Explorer.EmptySubtitle","أنشئ مجلدًا أو أضف وسائط. ستظهر العناصر المعلّقة الجديدة هنا فورًا."),("Pending.Title","التغييرات المعلّقة"),("Pending.Subtitle","راجع كل شيء قبل الكتابة على القرص."),
                ("AddMedia.Title","إضافة وسائط"),("AddMedia.Subtitle","ألصق فيديو أو قائمة تشغيل، راجع كل عنصر وأضف ما تريده فقط."),("AddMedia.UrlHint","ألصق رابط فيديو أو قائمة تشغيل YouTube"),("AddMedia.Analyze","تحليل"),("AddMedia.SelectAll","تحديد الكل"),("AddMedia.Mp3All","MP3 للجميع"),("AddMedia.Format","التنسيق"),("AddMedia.AudioQuality","جودة الصوت"),("AddMedia.VideoQuality","جودة الفيديو"),("AddMedia.NoMedia","ألصق رابط YouTube"),("AddMedia.NoMediaSubtitle","لن يتم تنزيل شيء أثناء التحليل. العناصر المحددة تصبح تغييرات معلّقة."),("AddMedia.Preparing","جارٍ تجهيز الوسائط…"),("AddMedia.PreparingSubtitle","جارٍ فحص محرك الوسائط وتحليل الرابط."),("AddMedia.Destination","الوجهة"),("AddMedia.Stage","إضافة إلى التنزيلات"),("AddMedia.Cancel","إلغاء"),
                ("Settings.Title","الإعدادات"),("Settings.Subtitle","خصص DownTrack بالطريقة التي تناسبك."),("Settings.Appearance","المظهر"),("Settings.AppearanceSubtitle","اختر كيف يتبع DownTrack سمة Windows."),("Settings.Language","اللغة"),("Settings.LanguageDescription","استخدم تلقائيًا لمتابعة لغة عرض Windows أو اختر لغة يدويًا."),("Settings.Automatic","تلقائي (Windows)"),("Settings.ThemeLight","فاتح"),("Settings.ThemeDark","داكن"),("Settings.ThemeSystem","النظام"),("Settings.Updates","التحديثات"),("Settings.UpdatesSubtitle","حافظ على تحديث التطبيق وأدوات الوسائط."),("Settings.AppUpdates","DownTrack"),("Settings.Check","تحقق"),("Settings.Update","تحديث"),("Settings.ToolUpdates","أدوات الوسائط"),("Settings.AutoUpdate","التحقق تلقائيًا من تحديثات DownTrack"),("Settings.AutoToolUpdate","تحديث أدوات الوسائط تلقائيًا"),("Settings.Defaults","إعدادات التنزيل الافتراضية"),("Settings.DefaultsSubtitle","تُستخدم هذه القيم عند تحليل وسائط جديدة."),("Settings.DefaultFormat","التنسيق الافتراضي"),("Settings.DefaultAudioQuality","جودة الصوت الافتراضية"),("Settings.DefaultVideoQuality","جودة الفيديو الافتراضية"),("Settings.Cancel","إلغاء"),("Settings.Save","حفظ الإعدادات")
            ),
            ["el"] = Pack(
                ("App.Settings","Ρυθμίσεις"),("Shell.AddMedia","Προσθήκη πολυμέσων"),("Shell.AddFolder","Προσθήκη φακέλου"),("Shell.Home","Αρχική"),("Shell.Forward","Μπροστά"),("Shell.Back","Πίσω"),("Shell.Library","Βιβλιοθήκη"),("Shell.Rename","Μετονομασία"),("Shell.Delete","Διαγραφή"),("Shell.Cancel","Ακύρωση"),("Shell.RootFolders","Βασικοί φάκελοι"),
                ("Library.Overline","Η ΒΙΒΛΙΟΘΗΚΗ ΜΟΥ"),("Library.Title","Η βιβλιοθήκη σας"),("Library.Subtitle","Οι φάκελοί σας, η οργάνωσή σας, ένας ήρεμος χώρος εργασίας."),("Library.Folder","ΦΑΚΕΛΟΣ"),("Library.Location","ΤΟΠΟΘΕΣΙΑ"),("Library.Action","ΕΝΕΡΓΕΙΑ"),("Library.Open","Άνοιγμα"),("Library.EmptyTitle","Η βιβλιοθήκη σας περιμένει τον πρώτο φάκελο"),("Library.EmptySubtitle","Επιλέξτε έναν φάκελο για διαχείριση από το DownTrack. Ο δίσκος δεν αλλάζει μέχρι να αποθηκεύσετε."),
                ("Explorer.Overline","ΒΙΒΛΙΟΘΗΚΗ / ΕΞΕΡΕΥΝΗΤΗΣ"),("Explorer.Name","ΟΝΟΜΑ"),("Explorer.Type","ΤΥΠΟΣ"),("Explorer.State","ΚΑΤΑΣΤΑΣΗ"),("Explorer.EmptyTitle","Αυτός ο φάκελος είναι κενός"),("Explorer.EmptySubtitle","Δημιουργήστε φάκελο ή προσθέστε πολυμέσα. Οι νέες εκκρεμότητες εμφανίζονται εδώ αμέσως."),("Pending.Title","Εκκρεμείς αλλαγές"),("Pending.Subtitle","Ελέγξτε τα πάντα πριν την εγγραφή στον δίσκο."),
                ("AddMedia.Title","Προσθήκη πολυμέσων"),("AddMedia.Subtitle","Επικολλήστε βίντεο ή playlist, ελέγξτε κάθε στοιχείο και προσθέστε μόνο ό,τι θέλετε."),("AddMedia.UrlHint","Επικολλήστε URL βίντεο ή playlist YouTube"),("AddMedia.Analyze","Ανάλυση"),("AddMedia.SelectAll","Επιλογή όλων"),("AddMedia.Mp3All","MP3 για όλα"),("AddMedia.Format","ΜΟΡΦΗ"),("AddMedia.AudioQuality","ΠΟΙΟΤΗΤΑ ΗΧΟΥ"),("AddMedia.VideoQuality","ΠΟΙΟΤΗΤΑ ΒΙΝΤΕΟ"),("AddMedia.NoMedia","Επικολλήστε σύνδεσμο YouTube"),("AddMedia.NoMediaSubtitle","Κατά την ανάλυση δεν γίνεται λήψη. Τα επιλεγμένα στοιχεία γίνονται εκκρεμείς αλλαγές."),("AddMedia.Preparing","Προετοιμασία πολυμέσων…"),("AddMedia.PreparingSubtitle","Έλεγχος της μηχανής πολυμέσων και ανάλυση του συνδέσμου."),("AddMedia.Destination","ΠΡΟΟΡΙΣΜΟΣ"),("AddMedia.Stage","Προσθήκη στις λήψεις"),("AddMedia.Cancel","Ακύρωση"),
                ("Settings.Title","Ρυθμίσεις"),("Settings.Subtitle","Προσαρμόστε το DownTrack όπως θέλετε."),("Settings.Appearance","Εμφάνιση"),("Settings.AppearanceSubtitle","Επιλέξτε πώς ακολουθεί το DownTrack το θέμα των Windows."),("Settings.Language","Γλώσσα"),("Settings.LanguageDescription","Χρησιμοποιήστε Αυτόματα για τη γλώσσα των Windows ή επιλέξτε γλώσσα χειροκίνητα."),("Settings.Automatic","Αυτόματα (Windows)"),("Settings.ThemeLight","Φωτεινό"),("Settings.ThemeDark","Σκοτεινό"),("Settings.ThemeSystem","Σύστημα"),("Settings.Updates","Ενημερώσεις"),("Settings.UpdatesSubtitle","Κρατήστε την εφαρμογή και τα εργαλεία πολυμέσων ενημερωμένα."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Έλεγχος"),("Settings.Update","Ενημέρωση"),("Settings.ToolUpdates","Εργαλεία πολυμέσων"),("Settings.AutoUpdate","Αυτόματος έλεγχος ενημερώσεων DownTrack"),("Settings.AutoToolUpdate","Αυτόματη ενημέρωση εργαλείων πολυμέσων"),("Settings.Defaults","Προεπιλεγμένες λήψεις"),("Settings.DefaultsSubtitle","Αυτές οι τιμές χρησιμοποιούνται κατά την ανάλυση νέων πολυμέσων."),("Settings.DefaultFormat","Προεπιλεγμένη μορφή"),("Settings.DefaultAudioQuality","Προεπιλεγμένη ποιότητα ήχου"),("Settings.DefaultVideoQuality","Προεπιλεγμένη ποιότητα βίντεο"),("Settings.Cancel","Ακύρωση"),("Settings.Save","Αποθήκευση ρυθμίσεων")
            ),
            ["ro"] = Pack(
                ("App.Settings","Setări"),("Shell.AddMedia","Adaugă media"),("Shell.AddFolder","Adaugă folder"),("Shell.Home","Acasă"),("Shell.Forward","Înainte"),("Shell.Back","Înapoi"),("Shell.Library","Bibliotecă"),("Shell.Rename","Redenumește"),("Shell.Delete","Șterge"),("Shell.Cancel","Anulează"),("Shell.RootFolders","Foldere rădăcină"),
                ("Library.Overline","BIBLIOTECA MEA"),("Library.Title","Biblioteca ta"),("Library.Subtitle","Folderele tale, organizarea ta, un spațiu de lucru liniștit."),("Library.Folder","FOLDER"),("Library.Location","LOCAȚIE"),("Library.Action","ACȚIUNE"),("Library.Open","Deschide"),("Library.EmptyTitle","Biblioteca ta așteaptă primul folder"),("Library.EmptySubtitle","Alege un folder administrat de DownTrack. Nimic nu se schimbă pe disc până nu salvezi."),
                ("Explorer.Overline","BIBLIOTECĂ / EXPLORATOR"),("Explorer.Name","NUME"),("Explorer.Type","TIP"),("Explorer.State","STARE"),("Explorer.EmptyTitle","Acest folder este gol"),("Explorer.EmptySubtitle","Creează un folder sau adaugă media. Elementele noi în așteptare apar imediat aici."),("Pending.Title","Modificări în așteptare"),("Pending.Subtitle","Verifică totul înainte de a scrie pe disc."),
                ("AddMedia.Title","Adaugă media"),("AddMedia.Subtitle","Lipește un videoclip sau un playlist, verifică fiecare element și adaugă doar ce dorești."),("AddMedia.UrlHint","Lipește URL-ul unui videoclip sau playlist YouTube"),("AddMedia.Analyze","Analizează"),("AddMedia.SelectAll","Selectează tot"),("AddMedia.Mp3All","MP3 pentru toate"),("AddMedia.Format","FORMAT"),("AddMedia.AudioQuality","CALITATE AUDIO"),("AddMedia.VideoQuality","CALITATE VIDEO"),("AddMedia.NoMedia","Lipește un link YouTube"),("AddMedia.NoMediaSubtitle","În timpul analizei nu se descarcă nimic. Elementele selectate devin modificări în așteptare."),("AddMedia.Preparing","Se pregătește media…"),("AddMedia.PreparingSubtitle","Se verifică motorul media și se analizează linkul."),("AddMedia.Destination","DESTINAȚIE"),("AddMedia.Stage","Adaugă la descărcări"),("AddMedia.Cancel","Anulează"),
                ("Settings.Title","Setări"),("Settings.Subtitle","Configurează DownTrack exact cum vrei."),("Settings.Appearance","Aspect"),("Settings.AppearanceSubtitle","Alege cum urmează DownTrack tema Windows."),("Settings.Language","Limbă"),("Settings.LanguageDescription","Folosește Automat pentru limba Windows sau alege manual."),("Settings.Automatic","Automat (Windows)"),("Settings.ThemeLight","Deschis"),("Settings.ThemeDark","Închis"),("Settings.ThemeSystem","Sistem"),("Settings.Updates","Actualizări"),("Settings.UpdatesSubtitle","Păstrează aplicația și instrumentele media actualizate."),("Settings.AppUpdates","DownTrack"),("Settings.Check","Verifică"),("Settings.Update","Actualizează"),("Settings.ToolUpdates","Instrumente media"),("Settings.AutoUpdate","Verifică automat actualizările DownTrack"),("Settings.AutoToolUpdate","Actualizează automat instrumentele media"),("Settings.Defaults","Setări implicite de descărcare"),("Settings.DefaultsSubtitle","Aceste valori sunt folosite la analizarea mediilor noi."),("Settings.DefaultFormat","Format implicit"),("Settings.DefaultAudioQuality","Calitate audio implicită"),("Settings.DefaultVideoQuality","Calitate video implicită"),("Settings.Cancel","Anulează"),("Settings.Save","Salvează setările")
            ),
            ["ja"] = Pack(
                ("App.Settings","設定"),("Shell.AddMedia","メディアを追加"),("Shell.AddFolder","フォルダーを追加"),("Shell.Home","ホーム"),("Shell.Forward","進む"),("Shell.Back","戻る"),("Shell.Library","ライブラリ"),("Shell.Rename","名前を変更"),("Shell.Delete","削除"),("Shell.Cancel","キャンセル"),("Shell.RootFolders","ルートフォルダー"),
                ("Library.Overline","マイライブラリ"),("Library.Title","あなたのライブラリ"),("Library.Subtitle","あなたのフォルダー、あなたの整理、落ち着いた作業スペース。"),("Library.Folder","フォルダー"),("Library.Location","場所"),("Library.Action","操作"),("Library.Open","開く"),("Library.EmptyTitle","ライブラリに最初のフォルダーを追加しましょう"),("Library.EmptySubtitle","DownTrackで管理するフォルダーを選択してください。保存するまでディスクは変更されません。"),
                ("Explorer.Overline","ライブラリ / エクスプローラー"),("Explorer.Name","名前"),("Explorer.Type","種類"),("Explorer.State","状態"),("Explorer.EmptyTitle","このフォルダーは空です"),("Explorer.EmptySubtitle","フォルダーを作成するかメディアを追加してください。保留中の項目はすぐに表示されます。"),("Pending.Title","保留中の変更"),("Pending.Subtitle","ディスクに書き込む前にすべて確認してください。"),
                ("AddMedia.Title","メディアを追加"),("AddMedia.Subtitle","動画またはプレイリストを貼り付け、各項目を確認して必要なものだけ追加します。"),("AddMedia.UrlHint","YouTube動画またはプレイリストのURLを貼り付け"),("AddMedia.Analyze","解析"),("AddMedia.SelectAll","すべて選択"),("AddMedia.Mp3All","すべてMP3"),("AddMedia.Format","形式"),("AddMedia.AudioQuality","音声品質"),("AddMedia.VideoQuality","動画品質"),("AddMedia.NoMedia","YouTubeリンクを貼り付け"),("AddMedia.NoMediaSubtitle","解析中はダウンロードされません。選択した項目は保留中の変更になります。"),("AddMedia.Preparing","メディアを準備しています…"),("AddMedia.PreparingSubtitle","メディアエンジンを確認してリンクを解析しています。"),("AddMedia.Destination","保存先"),("AddMedia.Stage","ダウンロードに追加"),("AddMedia.Cancel","キャンセル"),
                ("Settings.Title","設定"),("Settings.Subtitle","DownTrackを好みに合わせて設定します。"),("Settings.Appearance","外観"),("Settings.AppearanceSubtitle","DownTrackがWindowsテーマに従う方法を選択します。"),("Settings.Language","言語"),("Settings.LanguageDescription","Windowsの表示言語に従うには自動を使用するか、手動で選択してください。"),("Settings.Automatic","自動（Windows）"),("Settings.ThemeLight","ライト"),("Settings.ThemeDark","ダーク"),("Settings.ThemeSystem","システム"),("Settings.Updates","更新"),("Settings.UpdatesSubtitle","アプリとメディアツールを最新に保ちます。"),("Settings.AppUpdates","DownTrack"),("Settings.Check","確認"),("Settings.Update","更新"),("Settings.ToolUpdates","メディアツール"),("Settings.AutoUpdate","DownTrackの更新を自動確認"),("Settings.AutoToolUpdate","メディアツールを自動更新"),("Settings.Defaults","ダウンロードの既定値"),("Settings.DefaultsSubtitle","新しいメディアの解析時に使用します。"),("Settings.DefaultFormat","既定の形式"),("Settings.DefaultAudioQuality","既定の音声品質"),("Settings.DefaultVideoQuality","既定の動画品質"),("Settings.Cancel","キャンセル"),("Settings.Save","設定を保存")
            ),
            ["ko"] = Pack(
                ("App.Settings","설정"),("Shell.AddMedia","미디어 추가"),("Shell.AddFolder","폴더 추가"),("Shell.Home","홈"),("Shell.Forward","앞으로"),("Shell.Back","뒤로"),("Shell.Library","라이브러리"),("Shell.Rename","이름 바꾸기"),("Shell.Delete","삭제"),("Shell.Cancel","취소"),("Shell.RootFolders","루트 폴더"),
                ("Library.Overline","내 라이브러리"),("Library.Title","내 라이브러리"),("Library.Subtitle","내 폴더, 내 정리 방식, 차분한 작업 공간."),("Library.Folder","폴더"),("Library.Location","위치"),("Library.Action","동작"),("Library.Open","열기"),("Library.EmptyTitle","첫 번째 폴더를 기다리고 있습니다"),("Library.EmptySubtitle","DownTrack이 관리할 폴더를 선택하세요. 저장하기 전에는 디스크가 변경되지 않습니다."),
                ("Explorer.Overline","라이브러리 / 탐색기"),("Explorer.Name","이름"),("Explorer.Type","유형"),("Explorer.State","상태"),("Explorer.EmptyTitle","이 폴더는 비어 있습니다"),("Explorer.EmptySubtitle","폴더를 만들거나 미디어를 추가하세요. 대기 중인 새 항목이 바로 표시됩니다."),("Pending.Title","대기 중인 변경"),("Pending.Subtitle","디스크에 기록하기 전에 모든 항목을 검토하세요."),
                ("AddMedia.Title","미디어 추가"),("AddMedia.Subtitle","동영상이나 재생목록을 붙여넣고 각 항목을 검토한 뒤 원하는 항목만 추가하세요."),("AddMedia.UrlHint","YouTube 동영상 또는 재생목록 URL 붙여넣기"),("AddMedia.Analyze","분석"),("AddMedia.SelectAll","모두 선택"),("AddMedia.Mp3All","모두 MP3"),("AddMedia.Format","형식"),("AddMedia.AudioQuality","오디오 품질"),("AddMedia.VideoQuality","비디오 품질"),("AddMedia.NoMedia","YouTube 링크 붙여넣기"),("AddMedia.NoMediaSubtitle","분석 중에는 다운로드되지 않습니다. 선택한 항목은 대기 중인 변경이 됩니다."),("AddMedia.Preparing","미디어 준비 중…"),("AddMedia.PreparingSubtitle","미디어 엔진을 확인하고 링크를 분석하는 중입니다."),("AddMedia.Destination","대상"),("AddMedia.Stage","다운로드에 추가"),("AddMedia.Cancel","취소"),
                ("Settings.Title","설정"),("Settings.Subtitle","DownTrack을 원하는 대로 설정하세요."),("Settings.Appearance","모양"),("Settings.AppearanceSubtitle","DownTrack이 Windows 테마를 따르는 방식을 선택하세요."),("Settings.Language","언어"),("Settings.LanguageDescription","Windows 표시 언어를 사용하려면 자동을 선택하거나 직접 선택하세요."),("Settings.Automatic","자동 (Windows)"),("Settings.ThemeLight","밝게"),("Settings.ThemeDark","어둡게"),("Settings.ThemeSystem","시스템"),("Settings.Updates","업데이트"),("Settings.UpdatesSubtitle","앱과 미디어 도구를 최신 상태로 유지합니다."),("Settings.AppUpdates","DownTrack"),("Settings.Check","확인"),("Settings.Update","업데이트"),("Settings.ToolUpdates","미디어 도구"),("Settings.AutoUpdate","DownTrack 업데이트 자동 확인"),("Settings.AutoToolUpdate","미디어 도구 자동 업데이트"),("Settings.Defaults","다운로드 기본값"),("Settings.DefaultsSubtitle","새 미디어를 분석할 때 사용됩니다."),("Settings.DefaultFormat","기본 형식"),("Settings.DefaultAudioQuality","기본 오디오 품질"),("Settings.DefaultVideoQuality","기본 비디오 품질"),("Settings.Cancel","취소"),("Settings.Save","설정 저장")
            ),
            ["zh-Hans"] = Pack(
                ("App.Settings","设置"),("Shell.AddMedia","添加媒体"),("Shell.AddFolder","添加文件夹"),("Shell.Home","主页"),("Shell.Forward","前进"),("Shell.Back","后退"),("Shell.Library","媒体库"),("Shell.Rename","重命名"),("Shell.Delete","删除"),("Shell.Cancel","取消"),("Shell.RootFolders","根文件夹"),
                ("Library.Overline","我的媒体库"),("Library.Title","你的媒体库"),("Library.Subtitle","你的文件夹、你的整理方式、安静的工作空间。"),("Library.Folder","文件夹"),("Library.Location","位置"),("Library.Action","操作"),("Library.Open","打开"),("Library.EmptyTitle","媒体库正在等待第一个文件夹"),("Library.EmptySubtitle","选择一个由 DownTrack 管理的文件夹。保存之前不会更改磁盘。"),
                ("Explorer.Overline","媒体库 / 资源管理器"),("Explorer.Name","名称"),("Explorer.Type","类型"),("Explorer.State","状态"),("Explorer.EmptyTitle","此文件夹为空"),("Explorer.EmptySubtitle","创建文件夹或添加媒体。新的待处理项目会立即显示在这里。"),("Pending.Title","待处理更改"),("Pending.Subtitle","写入磁盘前请检查所有内容。"),
                ("AddMedia.Title","添加媒体"),("AddMedia.Subtitle","粘贴视频或播放列表，检查每个项目，只添加你需要的内容。"),("AddMedia.UrlHint","粘贴 YouTube 视频或播放列表网址"),("AddMedia.Analyze","分析"),("AddMedia.SelectAll","全选"),("AddMedia.Mp3All","全部 MP3"),("AddMedia.Format","格式"),("AddMedia.AudioQuality","音频质量"),("AddMedia.VideoQuality","视频质量"),("AddMedia.NoMedia","粘贴 YouTube 链接"),("AddMedia.NoMediaSubtitle","分析时不会下载任何内容。选择的项目会成为待处理更改。"),("AddMedia.Preparing","正在准备媒体…"),("AddMedia.PreparingSubtitle","正在检查媒体引擎并分析链接。"),("AddMedia.Destination","目标位置"),("AddMedia.Stage","添加到下载"),("AddMedia.Cancel","取消"),
                ("Settings.Title","设置"),("Settings.Subtitle","按你的方式自定义 DownTrack。"),("Settings.Appearance","外观"),("Settings.AppearanceSubtitle","选择 DownTrack 如何跟随 Windows 主题。"),("Settings.Language","语言"),("Settings.LanguageDescription","使用“自动”跟随 Windows 显示语言，或手动选择。"),("Settings.Automatic","自动（Windows）"),("Settings.ThemeLight","浅色"),("Settings.ThemeDark","深色"),("Settings.ThemeSystem","系统"),("Settings.Updates","更新"),("Settings.UpdatesSubtitle","保持应用和媒体工具为最新版本。"),("Settings.AppUpdates","DownTrack"),("Settings.Check","检查"),("Settings.Update","更新"),("Settings.ToolUpdates","媒体工具"),("Settings.AutoUpdate","自动检查 DownTrack 更新"),("Settings.AutoToolUpdate","自动更新媒体工具"),("Settings.Defaults","下载默认值"),("Settings.DefaultsSubtitle","分析新媒体时会使用这些值。"),("Settings.DefaultFormat","默认格式"),("Settings.DefaultAudioQuality","默认音频质量"),("Settings.DefaultVideoQuality","默认视频质量"),("Settings.Cancel","取消"),("Settings.Save","保存设置")
            ),
            ["zh-Hant"] = Pack(
                ("App.Settings","設定"),("Shell.AddMedia","新增媒體"),("Shell.AddFolder","新增資料夾"),("Shell.Home","首頁"),("Shell.Forward","前進"),("Shell.Back","返回"),("Shell.Library","媒體庫"),("Shell.Rename","重新命名"),("Shell.Delete","刪除"),("Shell.Cancel","取消"),("Shell.RootFolders","根資料夾"),
                ("Library.Overline","我的媒體庫"),("Library.Title","你的媒體庫"),("Library.Subtitle","你的資料夾、你的整理方式、安靜的工作空間。"),("Library.Folder","資料夾"),("Library.Location","位置"),("Library.Action","操作"),("Library.Open","開啟"),("Library.EmptyTitle","媒體庫正在等待第一個資料夾"),("Library.EmptySubtitle","選擇一個由 DownTrack 管理的資料夾。儲存之前不會變更磁碟。"),
                ("Explorer.Overline","媒體庫 / 檔案總管"),("Explorer.Name","名稱"),("Explorer.Type","類型"),("Explorer.State","狀態"),("Explorer.EmptyTitle","此資料夾是空的"),("Explorer.EmptySubtitle","建立資料夾或新增媒體。新的待處理項目會立即出現在這裡。"),("Pending.Title","待處理變更"),("Pending.Subtitle","寫入磁碟前請檢查所有內容。"),
                ("AddMedia.Title","新增媒體"),("AddMedia.Subtitle","貼上影片或播放清單，檢查每個項目，只新增你需要的內容。"),("AddMedia.UrlHint","貼上 YouTube 影片或播放清單網址"),("AddMedia.Analyze","分析"),("AddMedia.SelectAll","全選"),("AddMedia.Mp3All","全部 MP3"),("AddMedia.Format","格式"),("AddMedia.AudioQuality","音訊品質"),("AddMedia.VideoQuality","影片品質"),("AddMedia.NoMedia","貼上 YouTube 連結"),("AddMedia.NoMediaSubtitle","分析期間不會下載任何內容。選取的項目會成為待處理變更。"),("AddMedia.Preparing","正在準備媒體…"),("AddMedia.PreparingSubtitle","正在檢查媒體引擎並分析連結。"),("AddMedia.Destination","目的地"),("AddMedia.Stage","加入下載"),("AddMedia.Cancel","取消"),
                ("Settings.Title","設定"),("Settings.Subtitle","依照你的方式自訂 DownTrack。"),("Settings.Appearance","外觀"),("Settings.AppearanceSubtitle","選擇 DownTrack 如何跟隨 Windows 主題。"),("Settings.Language","語言"),("Settings.LanguageDescription","使用「自動」跟隨 Windows 顯示語言，或手動選擇。"),("Settings.Automatic","自動（Windows）"),("Settings.ThemeLight","淺色"),("Settings.ThemeDark","深色"),("Settings.ThemeSystem","系統"),("Settings.Updates","更新"),("Settings.UpdatesSubtitle","讓應用程式與媒體工具保持最新。"),("Settings.AppUpdates","DownTrack"),("Settings.Check","檢查"),("Settings.Update","更新"),("Settings.ToolUpdates","媒體工具"),("Settings.AutoUpdate","自動檢查 DownTrack 更新"),("Settings.AutoToolUpdate","自動更新媒體工具"),("Settings.Defaults","下載預設值"),("Settings.DefaultsSubtitle","分析新媒體時會使用這些值。"),("Settings.DefaultFormat","預設格式"),("Settings.DefaultAudioQuality","預設音訊品質"),("Settings.DefaultVideoQuality","預設影片品質"),("Settings.Cancel","取消"),("Settings.Save","儲存設定")
            )
        };

    private static Dictionary<string,string> Pack(params (string key,string value)[] values) =>
        values.ToDictionary(x => x.key, x => x.value, StringComparer.OrdinalIgnoreCase);
}
