using System;
using System.Collections.Generic;

namespace DownTrack.Infrastructure.Localization;

internal static class CompleteTranslationCatalog
{
    private static readonly string[] Languages =
    [
        "en","he","es","fr","de","it","pt","nl","pl","cs",
        "tr","uk","ru","ar","el","ro","ja","ko","zh-Hans","zh-Hant"
    ];

    private static readonly string[] Rows =
    [
        "Shell.AddMedia|Add media|הוסף מדיה|Añadir multimedia|Ajouter un média|Medien hinzufügen|Aggiungi media|Adicionar mídia|Media toevoegen|Dodaj multimedia|Přidat média|Medya ekle|Додати медіа|Добавить медиа|إضافة وسائط|Προσθήκη πολυμέσων|Adaugă media|メディアを追加|미디어 추가|添加媒体|新增媒體",
        "Shell.AddFolder|Add folder|הוסף תיקייה|Añadir carpeta|Ajouter un dossier|Ordner hinzufügen|Aggiungi cartella|Adicionar pasta|Map toevoegen|Dodaj folder|Přidat složku|Klasör ekle|Додати папку|Добавить папку|إضافة مجلد|Προσθήκη φακέλου|Adaugă folder|フォルダーを追加|폴더 추가|添加文件夹|新增資料夾",
        "Shell.Home|Home|בית|Inicio|Accueil|Startseite|Home|Início|Home|Strona główna|Domů|Ana sayfa|Головна|Главная|الرئيسية|Αρχική|Acasă|ホーム|홈|主页|首頁",
        "Shell.Forward|Forward|קדימה|Adelante|Avancer|Vorwärts|Avanti|Avançar|Vooruit|Dalej|Vpřed|İleri|Вперед|Вперед|التالي|Εμπρός|Înainte|進む|앞으로|前进|下一頁",
        "Shell.Back|Back|חזרה|Atrás|Retour|Zurück|Indietro|Voltar|Terug|Wstecz|Zpět|Geri|Назад|Назад|رجوع|Πίσω|Înapoi|戻る|뒤로|后退|上一頁",
        "Shell.Library|Library|ספרייה|Biblioteca|Bibliothèque|Bibliothek|Libreria|Biblioteca|Bibliotheek|Biblioteka|Knihovna|Kitaplık|Бібліотека|Библиотека|المكتبة|Βιβλιοθήκη|Bibliotecă|ライブラリ|라이브러리|媒体库|媒體庫",
        "Shell.Rename|Rename|שנה שם|Cambiar nombre|Renommer|Umbenennen|Rinomina|Renomear|Naam wijzigen|Zmień nazwę|Přejmenovat|Yeniden adlandır|Перейменувати|Переименовать|إعادة تسمية|Μετονομασία|Redenumește|名前を変更|이름 바꾸기|重命名|重新命名",
        "Shell.Delete|Delete|מחק|Eliminar|Supprimer|Löschen|Elimina|Excluir|Verwijderen|Usuń|Odstranit|Sil|Видалити|Удалить|حذف|Διαγραφή|Șterge|削除|삭제|删除|刪除",
        "Shell.Cancel|Cancel|ביטול|Cancelar|Annuler|Abbrechen|Annulla|Cancelar|Annuleren|Anuluj|Zrušit|İptal|Скасувати|Отмена|إلغاء|Ακύρωση|Anulează|キャンセル|취소|取消|取消",
        "Shell.MyLibrary|My Library|הספרייה שלי|Mi biblioteca|Ma bibliothèque|Meine Bibliothek|La mia libreria|Minha biblioteca|Mijn bibliotheek|Moja biblioteka|Moje knihovna|Kitaplığım|Моя бібліотека|Моя библиотека|مكتبتي|Η βιβλιοθήκη μου|Biblioteca mea|マイライブラリ|내 라이브러리|我的媒体库|我的媒體庫",
        "Shell.AllRootFolders|All root folders|כל תיקיות השורש|Todas las carpetas raíz|Tous les dossiers racine|Alle Stammordner|Tutte le cartelle radice|Todas as pastas raiz|Alle hoofd­mappen|Wszystkie foldery główne|Všechny kořenové složky|Tüm kök klasörler|Усі кореневі папки|Все корневые папки|كل المجلدات الجذر|Όλοι οι βασικοί φάκελοι|Toate folderele rădăcină|すべてのルートフォルダー|모든 루트 폴더|所有根文件夹|所有根資料夾",
        "Shell.EngineReady|Media engine ready|מנוע המדיה מוכן|Motor multimedia listo|Moteur multimédia prêt|Medien-Engine bereit|Motore multimediale pronto|Mecanismo de mídia pronto|Media-engine gereed|Silnik multimediów gotowy|Mediální engine připraven|Medya motoru hazır|Медіадвигун готовий|Медиа-движок готов|محرك الوسائط جاهز|Η μηχανή πολυμέσων είναι έτοιμη|Motorul media este pregătit|メディアエンジン準備完了|미디어 엔진 준비 완료|媒体引擎已就绪|媒體引擎已就緒",
        "Shell.EngineNeedsSetup|Media engine setup required|נדרשת הגדרת מנוע מדיה|Se requiere configurar el motor multimedia|Configuration du moteur multimédia requise|Einrichtung der Medien-Engine erforderlich|Configurazione del motore multimediale richiesta|É necessário configurar o mecanismo de mídia|Media-engine moet worden ingesteld|Wymagana konfiguracja silnika multimediów|Je nutné nastavit mediální engine|Medya motoru kurulumu gerekli|Потрібне налаштування медіадвигуна|Требуется настройка медиа-движка|مطلوب إعداد محرك الوسائط|Απαιτείται ρύθμιση της μηχανής πολυμέσων|Este necesară configurarea motorului media|メディアエンジンの設定が必要です|미디어 엔진 설정 필요|需要设置媒体引擎|需要設定媒體引擎",

        "Window.Minimize|Minimize|מזער|Minimizar|Réduire|Minimieren|Riduci|Minimizar|Minimaliseren|Minimalizuj|Minimalizovat|Küçült|Згорнути|Свернуть|تصغير|Ελαχιστοποίηση|Minimizează|最小化|최소화|最小化|最小化",
        "Window.Maximize|Maximize / restore|הגדל / שחזר|Maximizar / restaurar|Agrandir / restaurer|Maximieren / wiederherstellen|Massimizza / ripristina|Maximizar / restaurar|Maximaliseren / herstellen|Maksymalizuj / przywróć|Maximalizovat / obnovit|Büyüt / geri yükle|Розгорнути / відновити|Развернуть / восстановить|تكبير / استعادة|Μεγιστοποίηση / επαναφορά|Maximizează / restaurează|最大化 / 復元|최대화 / 복원|最大化 / 还原|最大化 / 還原",
        "Window.Close|Close|סגור|Cerrar|Fermer|Schließen|Chiudi|Fechar|Sluiten|Zamknij|Zavřít|Kapat|Закрити|Закрыть|إغلاق|Κλείσιμο|Închide|閉じる|닫기|关闭|關閉",

        "Library.Overline|MY LIBRARY|הספרייה שלי|MI BIBLIOTECA|MA BIBLIOTHÈQUE|MEINE BIBLIOTHEK|LA MIA LIBRERIA|MINHA BIBLIOTECA|MIJN BIBLIOTHEEK|MOJA BIBLIOTEKA|MOJE KNIHOVNA|KİTAPLIĞIM|МОЯ БІБЛІОТЕКА|МОЯ БИБЛИОТЕКА|مكتبتي|Η ΒΙΒΛΙΟΘΗΚΗ ΜΟΥ|BIBLIOTECA MEA|マイライブラリ|내 라이브러리|我的媒体库|我的媒體庫",
        "Library.Title|Your library|הספרייה שלך|Tu biblioteca|Votre bibliothèque|Deine Bibliothek|La tua libreria|Sua biblioteca|Jouw bibliotheek|Twoja biblioteka|Vaše knihovna|Kitaplığınız|Ваша бібліотека|Ваша библиотека|مكتبتك|Η βιβλιοθήκη σας|Biblioteca ta|あなたのライブラリ|라이브러리|你的媒体库|你的媒體庫",
        "Library.Subtitle|Your folders, your organization, one calm workspace.|התיקיות שלך, הארגון שלך, סביבת עבודה אחת ונעימה.|Tus carpetas, tu organización, un espacio de trabajo tranquilo.|Vos dossiers, votre organisation, un espace de travail serein.|Deine Ordner, deine Organisation, ein ruhiger Arbeitsbereich.|Le tue cartelle, la tua organizzazione, uno spazio di lavoro sereno.|Suas pastas, sua organização, um espaço de trabalho tranquilo.|Jouw mappen, jouw organisatie, één rustige werkruimte.|Twoje foldery, Twoja organizacja, jedna spokojna przestrzeń robocza.|Vaše složky, vaše organizace, jeden klidný pracovní prostor.|Klasörleriniz, düzeniniz, sakin bir çalışma alanı.|Ваші папки, ваша організація, один спокійний робочий простір.|Ваши папки, ваша организация, единое спокойное рабочее пространство.|مجلداتك وتنظيمك في مساحة عمل هادئة واحدة.|Οι φάκελοί σας, η οργάνωσή σας, ένας ήρεμος χώρος εργασίας.|Folderele tale, organizarea ta, un spațiu de lucru liniștit.|フォルダーも整理も、ひとつの落ち着いたワークスペースで。|폴더와 정리를 하나의 깔끔한 작업 공간에서 관리하세요.|你的文件夹、你的组织方式，都集中在一个舒适的工作区。|你的資料夾、你的整理方式，都集中在一個舒適的工作區。",
        "Library.Folder|FOLDER|תיקייה|CARPETA|DOSSIER|ORDNER|CARTELLA|PASTA|MAP|FOLDER|SLOŽKA|KLASÖR|ПАПКА|ПАПКА|مجلد|ΦΑΚΕΛΟΣ|FOLDER|フォルダー|폴더|文件夹|資料夾",
        "Library.Location|LOCATION|מיקום|UBICACIÓN|EMPLACEMENT|ORT|POSIZIONE|LOCAL|LOCATIE|LOKALIZACJA|UMÍSTĚNÍ|KONUM|РОЗТАШУВАННЯ|РАСПОЛОЖЕНИЕ|الموقع|ΤΟΠΟΘΕΣΙΑ|LOCAȚIE|場所|위치|位置|位置",
        "Library.Action|ACTION|פעולה|ACCIÓN|ACTION|AKTION|AZIONE|AÇÃO|ACTIE|AKCJA|AKCE|İŞLEM|ДІЯ|ДЕЙСТВИЕ|الإجراء|ΕΝΕΡΓΕΙΑ|ACȚIUNE|操作|작업|操作|操作",
                "Library.AddRootFolder|Add root folder|הוסף תיקיית שורש|Añadir carpeta raíz|Ajouter un dossier racine|Stammordner hinzufügen|Aggiungi cartella radice|Adicionar pasta raiz|Hoofdmap toevoegen|Dodaj folder główny|Přidat kořenovou složku|Kök klasör ekle|Додати кореневу папку|Добавить корневую папку|إضافة مجلد جذري|Προσθήκη βασικού φακέλου|Adaugă folder rădăcină|ルートフォルダーを追加|루트 폴더 추가|添加根文件夹|新增根資料夾",
"Library.Open|Open|פתח|Abrir|Ouvrir|Öffnen|Apri|Abrir|Openen|Otwórz|Otevřít|Aç|Відкрити|Открыть|فتح|Άνοιγμα|Deschide|開く|열기|打开|開啟",
        "Library.EmptyTitle|Your library is ready for its first folder|הספרייה שלך מחכה לתיקייה הראשונה|Tu biblioteca está lista para su primera carpeta|Votre bibliothèque attend son premier dossier|Deine Bibliothek wartet auf den ersten Ordner|La tua libreria è pronta per la prima cartella|Sua biblioteca está pronta para a primeira pasta|Je bibliotheek wacht op de eerste map|Twoja biblioteka czeka na pierwszy folder|Vaše knihovna čeká na první složku|Kitaplığınız ilk klasörü bekliyor|Ваша бібліотека чекає на першу папку|Ваша библиотека ждёт первую папку|مكتبتك جاهزة لمجلدك الأول|Η βιβλιοθήκη σας περιμένει τον πρώτο φάκελο|Biblioteca ta așteaptă primul folder|最初のフォルダーを追加しましょう|첫 번째 폴더를 추가하세요|你的媒体库正在等待第一个文件夹|你的媒體庫正在等待第一個資料夾",
        "Library.EmptySubtitle|Choose a folder to manage it inside DownTrack. Nothing changes on disk until you save.|בחר תיקייה לניהול בתוך DownTrack. שום דבר בדיסק לא משתנה עד ששומרים.|Elige una carpeta para administrarla en DownTrack. Nada cambia en el disco hasta que guardes.|Choisissez un dossier à gérer dans DownTrack. Rien ne change sur le disque avant l’enregistrement.|Wähle einen Ordner für DownTrack. Erst beim Speichern wird die Festplatte geändert.|Scegli una cartella da gestire in DownTrack. Nulla cambia sul disco finché non salvi.|Escolha uma pasta para gerenciar no DownTrack. Nada muda no disco até salvar.|Kies een map om in DownTrack te beheren. Er verandert niets op schijf totdat je opslaat.|Wybierz folder do zarządzania w DownTrack. Dysk nie zmieni się przed zapisaniem.|Vyberte složku pro správu v DownTrack. Na disku se nic nezmění, dokud neuložíte.|DownTrack'te yönetmek için bir klasör seçin. Kaydetmeden diskte hiçbir şey değişmez.|Виберіть папку для керування в DownTrack. На диску нічого не зміниться, доки ви не збережете.|Выберите папку для управления в DownTrack. На диске ничего не изменится до сохранения.|اختر مجلدًا لإدارته داخل DownTrack. لن يتغير القرص حتى تحفظ.|Επιλέξτε φάκελο για διαχείριση στο DownTrack. Τίποτα δεν αλλάζει στον δίσκο μέχρι την αποθήκευση.|Alege un folder de gestionat în DownTrack. Nimic nu se schimbă pe disc până când salvezi.|DownTrackで管理するフォルダーを選択してください。保存するまでディスクは変更されません。|DownTrack에서 관리할 폴더를 선택하세요. 저장하기 전에는 디스크가 변경되지 않습니다.|选择一个文件夹在 DownTrack 中管理。保存前不会更改磁盘。|選擇資料夾在 DownTrack 中管理。儲存前不會變更磁碟。",

        "Explorer.Overline|LIBRARY / EXPLORER|ספרייה / סייר|BIBLIOTECA / EXPLORADOR|BIBLIOTHÈQUE / EXPLORATEUR|BIBLIOTHEK / EXPLORER|LIBRERIA / ESPLORA|BIBLIOTECA / EXPLORADOR|BIBLIOTHEEK / VERKENNER|BIBLIOTEKA / EKSPLORATOR|KNIHOVNA / PRŮZKUMNÍK|KİTAPLIK / GEZGİN|БІБЛІОТЕКА / ПРОВІДНИК|БИБЛИОТЕКА / ПРОВОДНИК|المكتبة / المستكشف|ΒΙΒΛΙΟΘΗΚΗ / ΕΞΕΡΕΥΝΗΤΗΣ|BIBLIOTECĂ / EXPLORATOR|ライブラリ / エクスプローラー|라이브러리 / 탐색기|媒体库 / 资源管理器|媒體庫 / 檔案總管",
        "Explorer.Name|NAME|שם|NOMBRE|NOM|NAME|NOME|NOME|NAAM|NAZWA|NÁZEV|AD|ІМ'Я|ИМЯ|الاسم|ΟΝΟΜΑ|NUME|名前|이름|名称|名稱",
        "Explorer.Type|TYPE|סוג|TIPO|TYPE|TYP|TIPO|TIPO|TYPE|TYP|TYP|TÜR|ТИП|ТИП|النوع|ΤΥΠΟΣ|TIP|種類|유형|类型|類型",
        "Explorer.State|STATE|מצב|ESTADO|ÉTAT|STATUS|STATO|ESTADO|STATUS|STAN|STAV|DURUM|СТАН|СОСТОЯНИЕ|الحالة|ΚΑΤΑΣΤΑΣΗ|STARE|状態|상태|状态|狀態",
        "Explorer.EmptyTitle|This folder is empty|התיקייה ריקה|Esta carpeta está vacía|Ce dossier est vide|Dieser Ordner ist leer|Questa cartella è vuota|Esta pasta está vazia|Deze map is leeg|Ten folder jest pusty|Tato složka je prázdná|Bu klasör boş|Ця папка порожня|Эта папка пуста|هذا المجلد فارغ|Αυτός ο φάκελος είναι άδειος|Acest folder este gol|このフォルダーは空です|이 폴더는 비어 있습니다|此文件夹为空|此資料夾為空",
        "Explorer.EmptySubtitle|Create a folder or add media. New staged items appear here immediately.|צור תיקייה או הוסף מדיה. פריטים ממתינים חדשים יופיעו כאן מיד.|Crea una carpeta o añade medios. Los nuevos elementos pendientes aparecen aquí de inmediato.|Créez un dossier ou ajoutez un média. Les nouveaux éléments en attente apparaissent immédiatement.|Erstelle einen Ordner oder füge Medien hinzu. Neue vorgemerkte Elemente erscheinen sofort.|Crea una cartella o aggiungi media. I nuovi elementi in sospeso appaiono subito.|Crie uma pasta ou adicione mídia. Novos itens pendentes aparecem aqui imediatamente.|Maak een map of voeg media toe. Nieuwe wachtende items verschijnen direct.|Utwórz folder lub dodaj multimedia. Nowe oczekujące elementy pojawiają się od razu.|Vytvořte složku nebo přidejte média. Nové čekající položky se zobrazí okamžitě.|Klasör oluşturun veya medya ekleyin. Yeni bekleyen öğeler hemen görünür.|Створіть папку або додайте медіа. Нові очікувані елементи з'являться одразу.|Создайте папку или добавьте медиа. Новые ожидающие элементы появятся сразу.|أنشئ مجلدًا أو أضف وسائط. ستظهر العناصر المعلقة الجديدة هنا فورًا.|Δημιουργήστε φάκελο ή προσθέστε πολυμέσα. Τα νέα εκκρεμή στοιχεία εμφανίζονται αμέσως.|Creează un folder sau adaugă media. Elementele noi în așteptare apar imediat.|フォルダーを作成するかメディアを追加してください。新しい保留項目はすぐ表示されます。|폴더를 만들거나 미디어를 추가하세요. 새 대기 항목이 즉시 나타납니다.|创建文件夹或添加媒体。新的待处理项目会立即显示。|建立資料夾或新增媒體。新的待處理項目會立即顯示。",

        "Pending.Title|Pending changes|שינויים ממתינים|Cambios pendientes|Modifications en attente|Ausstehende Änderungen|Modifiche in sospeso|Alterações pendentes|Wachtende wijzigingen|Oczekujące zmiany|Čekající změny|Bekleyen değişiklikler|Очікувані зміни|Ожидающие изменения|تغييرات معلقة|Εκκρεμείς αλλαγές|Modificări în așteptare|保留中の変更|보류 중인 변경 사항|待处理更改|待處理變更",
        "Pending.CreateFolder|Pending: create “{0}”.|ממתין: יצירת „{0}“.|Pendiente: crear “{0}”.|En attente : créer « {0} ».|Ausstehend: „{0}“ erstellen.|In sospeso: crea “{0}”.|Pendente: criar “{0}”.|In afwachting: “{0}” maken.|Oczekuje: utworzenie „{0}”.|Čeká se: vytvořit „{0}“.|Bekliyor: “{0}” oluştur.|В очікуванні: створити «{0}».|Ожидается: создать «{0}».|معلق: إنشاء «{0}».|Σε αναμονή: δημιουργία «{0}».|În așteptare: creează „{0}”.|保留中: 「{0}」を作成します。|대기: “{0}” 만들기.|待处理：创建“{0}”。|待處理：建立「{0}」。",
        "Pending.Rename|Pending: rename “{0}” → “{1}”.|ממתין: שינוי השם של „{0}“ ל־„{1}“.|Pendiente: cambiar “{0}” por “{1}”.|En attente : renommer « {0} » en « {1} ».|Ausstehend: „{0}“ in „{1}“ umbenennen.|In sospeso: rinomina “{0}” in “{1}”.|Pendente: renomear “{0}” para “{1}”.|In afwachting: “{0}” hernoemen naar “{1}”.|Oczekuje: zmiana nazwy „{0}” na „{1}”.|Čeká se: přejmenovat „{0}“ na „{1}“.|Bekliyor: “{0}” → “{1}” yeniden adlandır.|В очікуванні: перейменувати «{0}» на «{1}».|Ожидается: переименовать «{0}» в «{1}».|معلق: إعادة تسمية «{0}» إلى «{1}».|Σε αναμονή: μετονομασία «{0}» σε «{1}».|În așteptare: redenumește „{0}” în „{1}”.|保留中: 「{0}」を「{1}」に変更します。|대기: “{0}”을(를) “{1}”(으)로 변경.|待处理：将“{0}”重命名为“{1}”。|待處理：將「{0}」重新命名為「{1}」。",
        "Pending.Delete|Pending: delete “{0}”.|ממתין: מחיקת „{0}“.|Pendiente: eliminar “{0}”.|En attente : supprimer « {0} ».|Ausstehend: „{0}“ löschen.|In sospeso: elimina “{0}”.|Pendente: excluir “{0}”.|In afwachting: “{0}” verwijderen.|Oczekuje: usunięcie „{0}”.|Čeká se: odstranit „{0}“.|Bekliyor: “{0}” sil.|В очікуванні: видалити «{0}».|Ожидается: удалить «{0}».|معلق: حذف «{0}».|Σε αναμονή: διαγραφή «{0}».|În așteptare: șterge „{0}”.|保留中: 「{0}」を削除します。|대기: “{0}” 삭제.|待处理：删除“{0}”。|待處理：刪除「{0}」。",
        "Pending.Download|Download: {0}|הורדה: {0}|Descarga: {0}|Téléchargement : {0}|Download: {0}|Download: {0}|Download: {0}|Download: {0}|Pobieranie: {0}|Stahování: {0}|İndirme: {0}|Завантаження: {0}|Загрузка: {0}|تنزيل: {0}|Λήψη: {0}|Descărcare: {0}|ダウンロード: {0}|다운로드: {0}|下载：{0}|下載：{0}",
        "Pending.Generic|Pending change|שינוי ממתין|Cambio pendiente|Modification en attente|Ausstehende Änderung|Modifica in sospeso|Alteração pendente|Wachtende wijziging|Oczekująca zmiana|Čekající změna|Bekleyen değişiklik|Очікувана зміна|Ожидающее изменение|تغيير معلق|Εκκρεμής αλλαγή|Modificare în așteptare|保留中の変更|대기 중인 변경|待处理更改|待處理變更",
        "Pending.Subtitle|Review everything before it touches your disk.|בדוק הכול לפני שמשהו נכתב לדיסק.|Revisa todo antes de escribir en el disco.|Vérifiez tout avant toute écriture sur le disque.|Prüfe alles, bevor etwas auf die Festplatte geschrieben wird.|Controlla tutto prima di scrivere sul disco.|Revise tudo antes de alterar o disco.|Controleer alles voordat het naar de schijf wordt geschreven.|Sprawdź wszystko przed zapisaniem na dysku.|Před zápisem na disk vše zkontrolujte.|Diske yazmadan önce her şeyi gözden geçirin.|Перевірте все перед записом на диск.|Проверьте всё до записи на диск.|راجع كل شيء قبل الكتابة على القرص.|Ελέγξτε τα πάντα πριν γραφτούν στον δίσκο.|Verifică totul înainte de scrierea pe disc.|ディスクに書き込む前にすべて確認してください。|디스크에 기록하기 전에 모든 항목을 검토하세요.|写入磁盘前先检查所有内容。|寫入磁碟前先檢查所有內容。",

        "AddMedia.Title|Add media|הוסף מדיה|Añadir multimedia|Ajouter un média|Medien hinzufügen|Aggiungi media|Adicionar mídia|Media toevoegen|Dodaj multimedia|Přidat média|Medya ekle|Додати медіа|Добавить медиа|إضافة وسائط|Προσθήκη πολυμέσων|Adaugă media|メディアを追加|미디어 추가|添加媒体|新增媒體",
        "AddMedia.Subtitle|Paste a video or playlist, review every item, then stage only what you want.|הדבק סרטון או פלייליסט, בדוק כל פריט ואז הוסף רק מה שתרצה.|Pega un vídeo o playlist, revisa cada elemento y añade solo lo que quieras.|Collez une vidéo ou une playlist, vérifiez chaque élément, puis ajoutez uniquement ce que vous voulez.|Füge Video oder Playlist ein, prüfe jeden Eintrag und übernimm nur Gewünschtes.|Incolla video o playlist, controlla ogni elemento e aggiungi solo ciò che vuoi.|Cole um vídeo ou playlist, revise cada item e adicione apenas o que quiser.|Plak een video of playlist, controleer elk item en voeg alleen toe wat je wilt.|Wklej film lub playlistę, sprawdź każdy element i dodaj tylko to, czego chcesz.|Vložte video nebo playlist, zkontrolujte položky a přidejte jen to, co chcete.|Video veya oynatma listesi yapıştırın, her öğeyi inceleyin ve yalnızca istediklerinizi ekleyin.|Вставте відео або плейлист, перегляньте кожен елемент і додайте лише потрібне.|Вставьте видео или плейлист, проверьте каждый элемент и добавьте только нужное.|ألصق فيديو أو قائمة تشغيل، وراجع كل عنصر ثم أضف ما تريد فقط.|Επικολλήστε βίντεο ή λίστα αναπαραγωγής, ελέγξτε κάθε στοιχείο και προσθέστε μόνο όσα θέλετε.|Lipește un videoclip sau un playlist, verifică fiecare element și adaugă doar ce vrei.|動画またはプレイリストを貼り付け、各項目を確認して必要なものだけ追加します。|동영상 또는 재생목록을 붙여 넣고 각 항목을 검토한 뒤 원하는 것만 추가하세요.|粘贴视频或播放列表，检查每个项目，然后只添加需要的内容。|貼上影片或播放清單，檢查每個項目後只新增需要的內容。",
        "AddMedia.UrlHint|Paste a YouTube video or playlist URL|הדבק קישור לסרטון או פלייליסט של YouTube|Pega la URL de un vídeo o playlist de YouTube|Collez l’URL d’une vidéo ou playlist YouTube|YouTube-Video- oder Playlist-URL einfügen|Incolla l’URL di un video o playlist YouTube|Cole o URL de um vídeo ou playlist do YouTube|Plak een YouTube-video- of playlist-URL|Wklej adres URL filmu lub playlisty YouTube|Vložte URL videa nebo playlistu YouTube|YouTube video veya oynatma listesi URL'si yapıştırın|Вставте URL відео або плейлиста YouTube|Вставьте URL видео или плейлиста YouTube|ألصق رابط فيديو أو قائمة تشغيل على YouTube|Επικολλήστε URL βίντεο ή playlist YouTube|Lipește URL-ul unui videoclip sau playlist YouTube|YouTube動画またはプレイリストのURLを貼り付け|YouTube 동영상 또는 재생목록 URL 붙여넣기|粘贴 YouTube 视频或播放列表 URL|貼上 YouTube 影片或播放清單 URL",
        "AddMedia.Analyze|Analyze|נתח|Analizar|Analyser|Analysieren|Analizza|Analisar|Analyseren|Analizuj|Analyzovat|Analiz et|Аналізувати|Анализировать|تحليل|Ανάλυση|Analizează|解析|분석|分析|分析",
        "AddMedia.SelectAll|Select all|בחר הכול|Seleccionar todo|Tout sélectionner|Alle auswählen|Seleziona tutto|Selecionar tudo|Alles selecteren|Zaznacz wszystko|Vybrat vše|Tümünü seç|Вибрати все|Выбрать всё|تحديد الكل|Επιλογή όλων|Selectează tot|すべて選択|모두 선택|全选|全選",
        "AddMedia.Mp3All|MP3 to all|MP3 לכולם|MP3 para todos|MP3 pour tous|MP3 für alle|MP3 per tutti|MP3 para todos|MP3 voor alles|MP3 dla wszystkich|MP3 pro všechny|Tümü için MP3|MP3 для всіх|MP3 для всех|MP3 للجميع|MP3 για όλους|MP3 pentru toate|すべてMP3|모두 MP3|全部设为 MP3|全部設為 MP3",
        "AddMedia.Format|FORMAT|פורמט|FORMATO|FORMAT|FORMAT|FORMATO|FORMATO|FORMAAT|FORMAT|FORMÁT|FORMAT|ФОРМАТ|ФОРМАТ|التنسيق|ΜΟΡΦΗ|FORMAT|形式|형식|格式|格式",
        "AddMedia.AudioQuality|AUDIO QUALITY|איכות שמע|CALIDAD DE AUDIO|QUALITÉ AUDIO|AUDIOQUALITÄT|QUALITÀ AUDIO|QUALIDADE DE ÁUDIO|AUDIOKWALITEIT|JAKOŚĆ AUDIO|KVALITA ZVUKU|SES KALİTESİ|ЯКІСТЬ АУДІО|КАЧЕСТВО АУДИО|جودة الصوت|ΠΟΙΟΤΗΤΑ ΗΧΟΥ|CALITATE AUDIO|音質|오디오 품질|音频质量|音訊品質",
        "AddMedia.VideoQuality|VIDEO QUALITY|איכות וידאו|CALIDAD DE VÍDEO|QUALITÉ VIDÉO|VIDEOQUALITÄT|QUALITÀ VIDEO|QUALIDADE DE VÍDEO|VIDEOKWALITEIT|JAKOŚĆ WIDEO|KVALITA VIDEA|VİDEO KALİTESİ|ЯКІСТЬ ВІДЕО|КАЧЕСТВО ВИДЕО|جودة الفيديو|ΠΟΙΟΤΗΤΑ ΒΙΝΤΕΟ|CALITATE VIDEO|画質|비디오 품질|视频质量|視訊品質",
        "AddMedia.NoMedia|Paste a YouTube link|הדבק קישור ל־YouTube|Pega un enlace de YouTube|Collez un lien YouTube|YouTube-Link einfügen|Incolla un link YouTube|Cole um link do YouTube|Plak een YouTube-link|Wklej link YouTube|Vložte odkaz YouTube|YouTube bağlantısı yapıştırın|Вставте посилання YouTube|Вставьте ссылку YouTube|ألصق رابط YouTube|Επικολλήστε σύνδεσμο YouTube|Lipește un link YouTube|YouTubeリンクを貼り付け|YouTube 링크 붙여넣기|粘贴 YouTube 链接|貼上 YouTube 連結",
        "AddMedia.NoMediaSubtitle|Nothing is downloaded during analysis. Selected items become pending changes.|בזמן הניתוח לא יורד דבר. הפריטים שנבחרו הופכים לשינויים ממתינים.|No se descarga nada durante el análisis. Los elementos seleccionados pasan a cambios pendientes.|Aucun téléchargement pendant l’analyse. Les éléments sélectionnés deviennent des modifications en attente.|Während der Analyse wird nichts heruntergeladen. Ausgewählte Elemente werden vorgemerkt.|Durante l’analisi non viene scaricato nulla. Gli elementi selezionati diventano modifiche in sospeso.|Nada é baixado durante a análise. Os itens selecionados viram alterações pendentes.|Tijdens de analyse wordt niets gedownload. Geselecteerde items worden wachtende wijzigingen.|Podczas analizy nic nie jest pobierane. Wybrane elementy stają się oczekującymi zmianami.|Během analýzy se nic nestahuje. Vybrané položky se stanou čekajícími změnami.|Analiz sırasında hiçbir şey indirilmez. Seçili öğeler bekleyen değişikliklere dönüşür.|Під час аналізу нічого не завантажується. Вибрані елементи стають очікуваними змінами.|Во время анализа ничего не скачивается. Выбранные элементы становятся ожидающими изменениями.|لا يتم تنزيل شيء أثناء التحليل. تصبح العناصر المحددة تغييرات معلقة.|Κατά την ανάλυση δεν γίνεται λήψη. Τα επιλεγμένα στοιχεία γίνονται εκκρεμείς αλλαγές.|Nu se descarcă nimic în timpul analizei. Elementele selectate devin modificări în așteptare.|解析中はダウンロードされません。選択項目は保留中の変更になります。|분석 중에는 아무것도 다운로드되지 않습니다. 선택한 항목은 대기 변경 사항이 됩니다.|分析期间不会下载任何内容。选中的项目会变成待处理更改。|分析期間不會下載任何內容。選取的項目會變成待處理變更。",
        "AddMedia.Preparing|Preparing media…|מכין מדיה…|Preparando multimedia…|Préparation du média…|Medien werden vorbereitet…|Preparazione media…|Preparando mídia…|Media voorbereiden…|Przygotowywanie multimediów…|Příprava médií…|Medya hazırlanıyor…|Підготовка медіа…|Подготовка медиа…|جارٍ تجهيز الوسائط…|Προετοιμασία πολυμέσων…|Se pregătesc mediile…|メディアを準備しています…|미디어 준비 중…|正在准备媒体…|正在準備媒體…",
        "AddMedia.PreparingSubtitle|Checking the media engine and analyzing the link.|בודק את מנוע המדיה ומנתח את הקישור.|Comprobando el motor multimedia y analizando el enlace.|Vérification du moteur multimédia et analyse du lien.|Medien-Engine wird geprüft und Link analysiert.|Controllo del motore multimediale e analisi del link.|Verificando o mecanismo de mídia e analisando o link.|Media-engine controleren en link analyseren.|Sprawdzanie silnika multimediów i analiza linku.|Kontrola mediálního enginu a analýza odkazu.|Medya motoru kontrol ediliyor ve bağlantı analiz ediliyor.|Перевірка медіадвигуна та аналіз посилання.|Проверка медиа-движка и анализ ссылки.|جارٍ التحقق من محرك الوسائط وتحليل الرابط.|Έλεγχος της μηχανής πολυμέσων και ανάλυση του συνδέσμου.|Se verifică motorul media și se analizează linkul.|メディアエンジンを確認してリンクを解析しています。|미디어 엔진을 확인하고 링크를 분석하는 중…|正在检查媒体引擎并分析链接。|正在檢查媒體引擎並分析連結。",
        "AddMedia.Destination|DESTINATION|יעד|DESTINO|DESTINATION|ZIEL|DESTINAZIONE|DESTINO|BESTEMMING|CEL|CÍL|HEDEF|ЦІЛЬ|ЦЕЛЬ|الوجهة|ΠΡΟΟΡΙΣΜΟΣ|DESTINAȚIE|保存先|대상|目标|目的地",
        "AddMedia.Stage|Add to downloads|הוסף להורדות|Añadir a descargas|Ajouter aux téléchargements|Zu Downloads hinzufügen|Aggiungi ai download|Adicionar aos downloads|Aan downloads toevoegen|Dodaj do pobierania|Přidat do stahování|İndirmelere ekle|Додати до завантажень|Добавить в загрузки|إضافة إلى التنزيلات|Προσθήκη στις λήψεις|Adaugă la descărcări|ダウンロードに追加|다운로드에 추가|添加到下载|新增至下載",
        "AddMedia.Cancel|Cancel|ביטול|Cancelar|Annuler|Abbrechen|Annulla|Cancelar|Annuleren|Anuluj|Zrušit|İptal|Скасувати|Отмена|إلغاء|Ακύρωση|Anulează|キャンセル|취소|取消|取消",

        "Settings.Title|Settings|הגדרות|Configuración|Paramètres|Einstellungen|Impostazioni|Configurações|Instellingen|Ustawienia|Nastavení|Ayarlar|Налаштування|Настройки|الإعدادات|Ρυθμίσεις|Setări|設定|설정|设置|設定",
        "Settings.Subtitle|Make DownTrack feel exactly the way you want.|התאם את DownTrack בדיוק בדרך שנוחה לך.|Haz que DownTrack funcione exactamente como quieres.|Personnalisez DownTrack comme vous le souhaitez.|Passe DownTrack genau an deine Wünsche an.|Configura DownTrack esattamente come preferisci.|Personalize o DownTrack exatamente como quiser.|Maak DownTrack precies zoals jij het wilt.|Dostosuj DownTrack dokładnie do siebie.|Přizpůsobte si DownTrack podle sebe.|DownTrack'i tam istediğiniz gibi ayarlayın.|Налаштуйте DownTrack саме під себе.|Настройте DownTrack под себя.|خصص DownTrack بالطريقة التي تريدها.|Προσαρμόστε το DownTrack όπως θέλετε.|Configurează DownTrack exact cum vrei.|DownTrackを好みに合わせて設定します。|DownTrack을 원하는 대로 설정하세요.|按你的方式定制 DownTrack。|依你的方式自訂 DownTrack。",
        "Settings.Appearance|Appearance|מראה|Apariencia|Apparence|Darstellung|Aspetto|Aparência|Weergave|Wygląd|Vzhled|Görünüm|Вигляд|Внешний вид|المظهر|Εμφάνιση|Aspect|外観|모양|外观|外觀",
        "Settings.AppearanceSubtitle|Choose how DownTrack follows your Windows theme.|בחר כיצד DownTrack עוקב אחר ערכת הצבעים של Windows.|Elige cómo DownTrack sigue el tema de Windows.|Choisissez comment DownTrack suit le thème de Windows.|Lege fest, wie DownTrack dem Windows-Design folgt.|Scegli come DownTrack segue il tema di Windows.|Escolha como o DownTrack segue o tema do Windows.|Kies hoe DownTrack het Windows-thema volgt.|Wybierz sposób dopasowania DownTrack do motywu Windows.|Zvolte, jak DownTrack sleduje motiv Windows.|DownTrack'in Windows temasını nasıl izleyeceğini seçin.|Виберіть, як DownTrack дотримується теми Windows.|Выберите, как DownTrack следует теме Windows.|اختر كيفية اتباع DownTrack لمظهر Windows.|Επιλέξτε πώς το DownTrack ακολουθεί το θέμα των Windows.|Alege modul în care DownTrack urmează tema Windows.|DownTrackがWindowsテーマに従う方法を選択してください。|DownTrack이 Windows 테마를 따르는 방식을 선택하세요.|选择 DownTrack 如何跟随 Windows 主题。|選擇 DownTrack 如何跟隨 Windows 主題。",
        "Settings.Language|Language|שפה|Idioma|Langue|Sprache|Lingua|Idioma|Taal|Język|Jazyk|Dil|Мова|Язык|اللغة|Γλώσσα|Limbă|言語|언어|语言|語言",
        "Settings.LanguageDescription|Use Automatic to follow your Windows display language, or choose a language manually.|בחר אוטומטי כדי לעקוב אחר שפת התצוגה של Windows, או בחר שפה ידנית.|Usa Automático para seguir el idioma de Windows o elige uno manualmente.|Utilisez Automatique pour suivre la langue de Windows ou choisissez une langue manuellement.|Verwende Automatisch für die Windows-Anzeigesprache oder wähle manuell.|Usa Automatico per seguire la lingua di Windows o scegli manualmente.|Use Automático para seguir o idioma do Windows ou escolha manualmente.|Gebruik Automatisch voor de Windows-weergavetaal of kies handmatig.|Użyj Automatycznie, aby korzystać z języka Windows, lub wybierz go ręcznie.|Použijte Automaticky podle jazyka Windows nebo vyberte ručně.|Windows görüntüleme dilini kullanmak için Otomatik'i seçin veya manuel bir dil seçin.|Використовуйте Автоматично для мови Windows або виберіть мову вручну.|Используйте Автоматически для языка Windows или выберите вручную.|استخدم تلقائيًا لمتابعة لغة عرض Windows أو اختر لغة يدويًا.|Χρησιμοποιήστε Αυτόματα για τη γλώσσα των Windows ή επιλέξτε χειροκίνητα.|Folosește Automat pentru limba Windows sau alege manual.|Windowsの表示言語に合わせるには自動を使用するか、手動で選択します。|Windows 표시 언어를 따르려면 자동을 선택하거나 직접 선택하세요.|选择“自动”跟随 Windows 显示语言，或手动选择语言。|選擇「自動」跟隨 Windows 顯示語言，或手動選擇。",
        "Settings.Automatic|Automatic (Windows)|אוטומטי (Windows)|Automático (Windows)|Automatique (Windows)|Automatisch (Windows)|Automatico (Windows)|Automático (Windows)|Automatisch (Windows)|Automatycznie (Windows)|Automaticky (Windows)|Otomatik (Windows)|Автоматично (Windows)|Автоматически (Windows)|تلقائي (Windows)|Αυτόματο (Windows)|Automat (Windows)|自動 (Windows)|자동 (Windows)|自动（Windows）|自動（Windows）",
        "Settings.ThemeLight|Light|בהיר|Claro|Clair|Hell|Chiaro|Claro|Licht|Jasny|Světlý|Açık|Світла|Светлая|فاتح|Φωτεινό|Luminos|ライト|밝게|浅色|淺色",
        "Settings.ThemeDark|Dark|כהה|Oscuro|Sombre|Dunkel|Scuro|Escuro|Donker|Ciemny|Tmavý|Koyu|Темна|Тёмная|داكن|Σκούρο|Întunecat|ダーク|어둡게|深色|深色",
        "Settings.ThemeSystem|System|מערכת|Sistema|Système|System|Sistema|Sistema|Systeem|Systemowy|Systém|Sistem|Система|Системная|النظام|Σύστημα|Sistem|システム|시스템|系统|系統",
        "Settings.Updates|Updates|עדכונים|Actualizaciones|Mises à jour|Updates|Aggiornamenti|Atualizações|Updates|Aktualizacje|Aktualizace|Güncellemeler|Оновлення|Обновления|التحديثات|Ενημερώσεις|Actualizări|更新|업데이트|更新|更新",
        "Settings.UpdatesSubtitle|Keep the app and media tools current.|שמור על התוכנה ועל כלי המדיה מעודכנים.|Mantén actualizados la aplicación y los medios.|Gardez l’application et les outils multimédias à jour.|Halte App und Medienwerkzeuge aktuell.|Mantieni aggiornati l’app e gli strumenti multimediali.|Mantenha o app e as ferramentas de mídia atualizados.|Houd de app en media-tools actueel.|Aktualizuj aplikację i narzędzia multimedialne.|Udržujte aplikaci a mediální nástroje aktuální.|Uygulamayı ve medya araçlarını güncel tutun.|Оновлюйте програму та медіадвигун.|Держите приложение и медиа-инструменты в актуальном состоянии.|حافظ على تحديث التطبيق وأدوات الوسائط.|Διατηρήστε την εφαρμογή και τα εργαλεία πολυμέσων ενημερωμένα.|Păstrează aplicația și instrumentele media actualizate.|アプリとメディアツールを最新に保ちます。|앱과 미디어 도구를 최신 상태로 유지하세요.|保持应用和媒体工具为最新版本。|保持應用程式與媒體工具為最新版本。",
        "Settings.AppUpdates|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack|DownTrack",
        "Settings.ToolUpdates|Media tools|כלי מדיה|Herramientas multimedia|Outils multimédias|Medienwerkzeuge|Strumenti multimediali|Ferramentas de mídia|Media-tools|Narzędzia multimedialne|Mediální nástroje|Medya araçları|Медіа-інструменти|Медиа-инструменты|أدوات الوسائط|Εργαλεία πολυμέσων|Instrumente media|メディアツール|미디어 도구|媒体工具|媒體工具",
        "Settings.Check|Check|בדוק|Comprobar|Vérifier|Prüfen|Controlla|Verificar|Controleren|Sprawdź|Zkontrolovat|Kontrol et|Перевірити|Проверить|تحقق|Έλεγχος|Verifică|確認|확인|检查|檢查",
        "Settings.Update|Update|עדכן|Actualizar|Mettre à jour|Aktualisieren|Aggiorna|Atualizar|Bijwerken|Aktualizuj|Aktualizovat|Güncelle|Оновити|Обновить|تحديث|Ενημέρωση|Actualizează|更新|업데이트|更新|更新",
        "Settings.AutoUpdate|Automatically check for DownTrack updates|בדוק אוטומטית עדכונים ל־DownTrack|Comprobar automáticamente las actualizaciones de DownTrack|Vérifier automatiquement les mises à jour de DownTrack|Automatisch nach DownTrack-Updates suchen|Controlla automaticamente gli aggiornamenti di DownTrack|Verificar automaticamente atualizações do DownTrack|Automatisch controleren op DownTrack-updates|Automatycznie sprawdzaj aktualizacje DownTrack|Automaticky kontrolovat aktualizace DownTrack|DownTrack güncellemelerini otomatik kontrol et|Автоматично перевіряти оновлення DownTrack|Автоматически проверять обновления DownTrack|التحقق تلقائيًا من تحديثات DownTrack|Αυτόματος έλεγχος ενημερώσεων DownTrack|Verifică automat actualizările DownTrack|DownTrackの更新を自動的に確認|DownTrack 업데이트 자동 확인|自动检查 DownTrack 更新|自動檢查 DownTrack 更新",
        "Settings.AutoToolUpdate|Automatically keep media tools current|שמור אוטומטית על כלי המדיה מעודכנים|Mantener automáticamente actualizadas las herramientas multimedia|Maintenir automatiquement les outils multimédias à jour|Medienwerkzeuge automatisch aktuell halten|Mantieni automaticamente aggiornati gli strumenti multimediali|Manter automaticamente as ferramentas de mídia atualizadas|Media-tools automatisch actueel houden|Automatycznie aktualizuj narzędzia multimedialne|Automaticky aktualizovat mediální nástroje|Medya araçlarını otomatik güncel tut|Автоматично оновлювати медіа-інструменти|Автоматически обновлять медиа-инструменты|الحفاظ تلقائيًا على تحديث أدوات الوسائط|Αυτόματη ενημέρωση των εργαλείων πολυμέσων|Actualizează automat instrumentele media|メディアツールを自動更新|미디어 도구 자동 업데이트|自动保持媒体工具为最新|自動保持媒體工具最新",
        "Settings.Defaults|Download defaults|ברירות מחדל להורדה|Valores predeterminados de descarga|Paramètres de téléchargement|Download-Standards|Predefiniti di download|Padrões de download|Standaard downloadinstellingen|Domyślne ustawienia pobierania|Výchozí nastavení stahování|İndirme varsayılanları|Параметри завантаження за замовчуванням|Настройки загрузки по умолчанию|إعدادات التنزيل الافتراضية|Προεπιλογές λήψης|Setări implicite de descărcare|ダウンロードの既定値|다운로드 기본값|下载默认设置|下載預設值",
        "Settings.DefaultsSubtitle|These values are used when new media is analyzed.|הערכים האלה ישמשו בעת ניתוח מדיה חדשה.|Estos valores se usan al analizar nuevos medios.|Ces valeurs sont utilisées lors de l’analyse de nouveaux médias.|Diese Werte werden bei neuen Medien verwendet.|Questi valori vengono usati per i nuovi media.|Esses valores são usados ao analisar novas mídias.|Deze waarden worden gebruikt bij nieuwe media.|Te wartości są używane dla nowych multimediów.|Tyto hodnoty se použijí při analýze nových médií.|Bu değerler yeni medya analiz edilirken kullanılır.|Ці значення використовуються під час аналізу нових медіа.|Эти значения используются при анализе нового медиа.|تُستخدم هذه القيم عند تحليل الوسائط الجديدة.|Αυτές οι τιμές χρησιμοποιούνται κατά την ανάλυση νέων πολυμέσων.|Aceste valori sunt folosite pentru media nouă.|新しいメディアの解析時に使用されます。|새 미디어를 분석할 때 이 값을 사용합니다.|分析新媒体时将使用这些值。|分析新媒體時會使用這些值。",
        "Settings.DefaultFormat|Default format|פורמט ברירת מחדל|Formato predeterminado|Format par défaut|Standardformat|Formato predefinito|Formato padrão|Standaardformaat|Domyślny format|Výchozí formát|Varsayılan format|Формат за замовчуванням|Формат по умолчанию|التنسيق الافتراضي|Προεπιλεγμένη μορφή|Format implicit|既定の形式|기본 형식|默认格式|預設格式",
        "Settings.DefaultAudioQuality|Default audio quality|איכות שמע כברירת מחדל|Calidad de audio predeterminada|Qualité audio par défaut|Standard-Audioqualität|Qualità audio predefinita|Qualidade de áudio padrão|Standaard audiokwaliteit|Domyślna jakość audio|Výchozí kvalita zvuku|Varsayılan ses kalitesi|Якість аудіо за замовчуванням|Качество аудио по умолчанию|جودة الصوت الافتراضية|Προεπιλεγμένη ποιότητα ήχου|Calitate audio implicită|既定の音質|기본 오디오 품질|默认音频质量|預設音訊品質",
        "Settings.DefaultVideoQuality|Default video quality|איכות וידאו כברירת מחדל|Calidad de vídeo predeterminada|Qualité vidéo par défaut|Standard-Videoqualität|Qualità video predefinita|Qualidade de vídeo padrão|Standaard videokwaliteit|Domyślna jakość wideo|Výchozí kvalita videa|Varsayılan video kalitesi|Якість відео за замовчуванням|Качество видео по умолчанию|جودة الفيديو الافتراضية|Προεπιλεγμένη ποιότητα βίντεο|Calitate video implicită|既定の画質|기본 비디오 품질|默认视频质量|預設視訊品質",
        "Settings.Cancel|Cancel|ביטול|Cancelar|Annuler|Abbrechen|Annulla|Cancelar|Annuleren|Anuluj|Zrušit|İptal|Скасувати|Отмена|إلغاء|Ακύρωση|Anulează|キャンセル|취소|取消|取消",
        "Settings.Save|Save settings|שמור הגדרות|Guardar configuración|Enregistrer les paramètres|Einstellungen speichern|Salva impostazioni|Salvar configurações|Instellingen opslaan|Zapisz ustawienia|Uložit nastavení|Ayarları kaydet|Зберегти налаштування|Сохранить настройки|حفظ الإعدادات|Αποθήκευση ρυθμίσεων|Salvează setările|設定を保存|설정 저장|保存设置|儲存設定",
        "Settings.ToolsReady|Media tools are ready.|כלי המדיה מוכנים.|Las herramientas multimedia están listas.|Les outils multimédias sont prêts.|Medienwerkzeuge sind bereit.|Gli strumenti multimediali sono pronti.|As ferramentas de mídia estão prontas.|Media-tools zijn gereed.|Narzędzia multimedialne są gotowe.|Mediální nástroje jsou připravené.|Medya araçları hazır.|Медіа-інструменти готові.|Медиа-инструменты готовы.|أدوات الوسائط جاهزة.|Τα εργαλεία πολυμέσων είναι έτοιμα.|Instrumentele media sunt pregătite.|メディアツールの準備ができました。|미디어 도구가 준비되었습니다.|媒体工具已准备就绪。|媒體工具已準備就緒。",
        "Settings.ToolsMissing|One or more media tools are missing.|אחד או יותר מכלי המדיה חסרים.|Faltan una o más herramientas multimedia.|Un ou plusieurs outils multimédias sont manquants.|Mindestens ein Medienwerkzeug fehlt.|Manca uno o più strumenti multimediali.|Uma ou mais ferramentas de mídia estão faltando.|Een of meer media-tools ontbreken.|Brakuje co najmniej jednego narzędzia multimedialnego.|Chybí jeden nebo více mediálních nástrojů.|Bir veya daha fazla medya aracı eksik.|Відсутній один або кілька медіа-інструментів.|Отсутствует один или несколько медиа-инструментов.|أداة وسائط واحدة أو أكثر مفقودة.|Λείπει ένα ή περισσότερα εργαλεία πολυμέσων.|Lipsește unul sau mai multe instrumente media.|1つ以上のメディアツールがありません。|하나 이상의 미디어 도구가 없습니다.|缺少一个或多个媒体工具。|缺少一個或多個媒體工具。",
        "Settings.ToolsUpdated|Media tools updated.|כלי המדיה עודכנו.|Herramientas multimedia actualizadas.|Outils multimédias mis à jour.|Medienwerkzeuge aktualisiert.|Strumenti multimediali aggiornati.|Ferramentas de mídia atualizadas.|Media-tools bijgewerkt.|Narzędzia multimedialne zaktualizowane.|Mediální nástroje aktualizovány.|Medya araçları güncellendi.|Медіа-інструменти оновлено.|Медиа-инструменты обновлены.|تم تحديث أدوات الوسائط.|Τα εργαλεία πολυμέσων ενημερώθηκαν.|Instrumentele media au fost actualizate.|メディアツールを更新しました。|미디어 도구가 업데이트되었습니다.|媒体工具已更新。|媒體工具已更新。",
        "Settings.CurrentVersion|Current version: {0}|גרסה נוכחית: {0}|Versión actual: {0}|Version actuelle : {0}|Aktuelle Version: {0}|Versione attuale: {0}|Versão atual: {0}|Huidige versie: {0}|Bieżąca wersja: {0}|Aktuální verze: {0}|Geçerli sürüm: {0}|Поточна версія: {0}|Текущая версия: {0}|الإصدار الحالي: {0}|Τρέχουσα έκδοση: {0}|Versiunea curentă: {0}|現在のバージョン: {0}|현재 버전: {0}|当前版本：{0}|目前版本：{0}",

        "Updates.Checking|Checking for updates…|בודק עדכונים…|Buscando actualizaciones…|Recherche de mises à jour…|Suche nach Updates…|Verifica aggiornamenti…|Verificando atualizações…|Controleren op updates…|Sprawdzanie aktualizacji…|Kontrola aktualizací…|Güncellemeler denetleniyor…|Перевірка оновлень…|Проверка обновлений…|جارٍ البحث عن التحديثات…|Έλεγχος ενημερώσεων…|Se verifică actualizările…|更新を確認しています…|업데이트 확인 중…|正在检查更新…|正在檢查更新…",
        "Updates.CheckFailed|Update check failed: {0}|בדיקת העדכון נכשלה: {0}|La comprobación de actualizaciones falló: {0}|Échec de la vérification : {0}|Updateprüfung fehlgeschlagen: {0}|Controllo aggiornamenti non riuscito: {0}|Falha ao verificar atualização: {0}|Updatecontrole mislukt: {0}|Sprawdzanie aktualizacji nie powiodło się: {0}|Kontrola aktualizací selhala: {0}|Güncelleme denetimi başarısız: {0}|Перевірка оновлень не вдалася: {0}|Проверка обновлений не удалась: {0}|فشل التحقق من التحديث: {0}|Αποτυχία ελέγχου ενημερώσεων: {0}|Verificarea actualizărilor a eșuat: {0}|更新の確認に失敗しました: {0}|업데이트 확인 실패: {0}|更新检查失败：{0}|更新檢查失敗：{0}",
        "Updates.Downloading|Downloading the latest version…|מוריד את הגרסה האחרונה…|Descargando la última versión…|Téléchargement de la dernière version…|Neueste Version wird heruntergeladen…|Download dell’ultima versione…|Baixando a versão mais recente…|Nieuwste versie downloaden…|Pobieranie najnowszej wersji…|Stahování nejnovější verze…|En yeni sürüm indiriliyor…|Завантаження останньої версії…|Загрузка последней версии…|جارٍ تنزيل أحدث إصدار…|Λήψη της τελευταίας έκδοσης…|Se descarcă ultima versiune…|最新バージョンをダウンロードしています…|최신 버전 다운로드 중…|正在下载最新版本…|正在下載最新版本…",
        "Updates.Restarting|Update started. DownTrack will restart when ready.|העדכון התחיל. DownTrack יופעל מחדש כשיהיה מוכן.|La actualización ha comenzado. DownTrack se reiniciará cuando esté listo.|La mise à jour a commencé. DownTrack redémarrera lorsqu’il sera prêt.|Das Update wurde gestartet. DownTrack wird neu gestartet.|L’aggiornamento è iniziato. DownTrack verrà riavviato.|A atualização começou. O DownTrack será reiniciado.|De update is gestart. DownTrack wordt opnieuw gestart.|Aktualizacja rozpoczęta. DownTrack uruchomi się ponownie.|Aktualizace byla spuštěna. DownTrack se restartuje.|Güncelleme başladı. DownTrack yeniden başlatılacak.|Оновлення розпочато. DownTrack перезапуститься.|Обновление началось. DownTrack перезапустится.|بدأ التحديث. سيتم إعادة تشغيل DownTrack.|Η ενημέρωση ξεκίνησε. Το DownTrack θα επανεκκινηθεί.|Actualizarea a început. DownTrack va reporni.|更新を開始しました。準備ができたらDownTrackを再起動します。|업데이트가 시작되었습니다. DownTrack이 다시 시작됩니다.|更新已开始。准备就绪后 DownTrack 将重启。|更新已開始。準備就緒後 DownTrack 將重新啟動。",

        "Engine.Setup|Setup|הגדרה|Configurar|Configurer|Einrichten|Configura|Configurar|Instellen|Konfiguruj|Nastavit|Kur|Налаштувати|Настроить|إعداد|Ρύθμιση|Configurare|セットアップ|설정|设置|設定",
        "Engine.DownloadingYtDlp|Downloading yt-dlp…|מוריד yt-dlp…|Descargando yt-dlp…|Téléchargement de yt-dlp…|yt-dlp wird heruntergeladen…|Download di yt-dlp…|Baixando yt-dlp…|yt-dlp downloaden…|Pobieranie yt-dlp…|Stahování yt-dlp…|yt-dlp indiriliyor…|Завантаження yt-dlp…|Загрузка yt-dlp…|جارٍ تنزيل yt-dlp…|Λήψη yt-dlp…|Se descarcă yt-dlp…|yt-dlpをダウンロードしています…|yt-dlp 다운로드 중…|正在下载 yt-dlp…|正在下載 yt-dlp…",
        "Engine.DownloadingFfmpeg|Downloading FFmpeg…|מוריד FFmpeg…|Descargando FFmpeg…|Téléchargement de FFmpeg…|FFmpeg wird heruntergeladen…|Download di FFmpeg…|Baixando FFmpeg…|FFmpeg downloaden…|Pobieranie FFmpeg…|Stahování FFmpeg…|FFmpeg indiriliyor…|Завантаження FFmpeg…|Загрузка FFmpeg…|جارٍ تنزيل FFmpeg…|Λήψη FFmpeg…|Se descarcă FFmpeg…|FFmpegをダウンロードしています…|FFmpeg 다운로드 중…|正在下载 FFmpeg…|正在下載 FFmpeg…",
        "Engine.InstallingRuntime|Installing Deno runtime…|מתקין את Deno…|Instalando Deno…|Installation de Deno…|Deno wird installiert…|Installazione di Deno…|Instalando Deno…|Deno installeren…|Instalowanie Deno…|Instalace Deno…|Deno kuruluyor…|Встановлення Deno…|Установка Deno…|جارٍ تثبيت Deno…|Εγκατάσταση Deno…|Se instalează Deno…|Denoをインストールしています…|Deno 설치 중…|正在安装 Deno…|正在安裝 Deno…",
        "Engine.Ready|Media engine ready.|מנוע המדיה מוכן.|Motor multimedia listo.|Moteur multimédia prêt.|Medien-Engine bereit.|Motore multimediale pronto.|Mecanismo de mídia pronto.|Media-engine gereed.|Silnik multimediów gotowy.|Mediální engine připraven.|Medya motoru hazır.|Медіадвигун готовий.|Медиа-движок готов.|محرك الوسائط جاهز.|Η μηχανή πολυμέσων είναι έτοιμη.|Motorul media este pregătit.|メディアエンジン準備完了。|미디어 엔진 준비 완료.|媒体引擎已就绪。|媒體引擎已就緒。",
        "Engine.VerifyingFfmpeg|Verifying FFmpeg…|מאמת FFmpeg…|Verificando FFmpeg…|Vérification de FFmpeg…|FFmpeg wird überprüft…|Verifica di FFmpeg…|Verificando FFmpeg…|FFmpeg verifiëren…|Weryfikowanie FFmpeg…|Ověřování FFmpeg…|FFmpeg doğrulanıyor…|Перевірка FFmpeg…|Проверка FFmpeg…|جارٍ التحقق من FFmpeg…|Επαλήθευση FFmpeg…|Se verifică FFmpeg…|FFmpegを検証しています…|FFmpeg 검증 중…|正在验证 FFmpeg…|正在驗證 FFmpeg…",
        "Engine.UpdatingYtDlp|Updating yt-dlp…|מעדכן yt-dlp…|Actualizando yt-dlp…|Mise à jour de yt-dlp…|yt-dlp wird aktualisiert…|Aggiornamento di yt-dlp…|Atualizando yt-dlp…|yt-dlp bijwerken…|Aktualizowanie yt-dlp…|Aktualizace yt-dlp…|yt-dlp güncelleniyor…|Оновлення yt-dlp…|Обновление yt-dlp…|جارٍ تحديث yt-dlp…|Ενημέρωση yt-dlp…|Se actualizează yt-dlp…|yt-dlpを更新しています…|yt-dlp 업데이트 중…|正在更新 yt-dlp…|正在更新 yt-dlp…",
        "Engine.UpdatingFfmpeg|Updating FFmpeg…|מעדכן FFmpeg…|Actualizando FFmpeg…|Mise à jour de FFmpeg…|FFmpeg wird aktualisiert…|Aggiornamento di FFmpeg…|Atualizando FFmpeg…|FFmpeg bijwerken…|Aktualizowanie FFmpeg…|Aktualizace FFmpeg…|FFmpeg güncelleniyor…|Оновлення FFmpeg…|Обновление FFmpeg…|جارٍ تحديث FFmpeg…|Ενημέρωση FFmpeg…|Se actualizează FFmpeg…|FFmpegを更新しています…|FFmpeg 업데이트 중…|正在更新 FFmpeg…|正在更新 FFmpeg…",
        "Engine.UpdatingDeno|Updating Deno…|מעדכן Deno…|Actualizando Deno…|Mise à jour de Deno…|Deno wird aktualisiert…|Aggiornamento di Deno…|Atualizando Deno…|Deno bijwerken…|Aktualizowanie Deno…|Aktualizace Deno…|Deno güncelleniyor…|Оновлення Deno…|Обновление Deno…|جارٍ تحديث Deno…|Ενημέρωση Deno…|Se actualizează Deno…|Denoを更新しています…|Deno 업데이트 중…|正在更新 Deno…|正在更新 Deno…",
        "Engine.Updated|Media tools updated.|כלי המדיה עודכנו.|Herramientas multimedia actualizadas.|Outils multimédias mis à jour.|Medienwerkzeuge aktualisiert.|Strumenti multimediali aggiornati.|Ferramentas de mídia atualizadas.|Media-tools bijgewerkt.|Narzędzia multimedialne zaktualizowane.|Mediální nástroje aktualizovány.|Medya araçları güncellendi.|Медіа-інструменти оновлено.|Медиа-инструменты обновлены.|تم تحديث أدوات الوسائط.|Τα εργαλεία πολυμέσων ενημερώθηκαν.|Instrumentele media au fost actualizate.|メディアツールを更新しました。|미디어 도구가 업데이트되었습니다.|媒体工具已更新。|媒體工具已更新。",
        "Engine.HashMissingFile|Checksum is missing for {0}.|חסר checksum עבור {0}.|Falta el checksum para {0}.|Le checksum manque pour {0}.|Checksum für {0} fehlt.|Checksum mancante per {0}.|O checksum está ausente para {0}.|Checksum ontbreekt voor {0}.|Brak sumy kontrolnej dla {0}.|Chybí kontrolní součet pro {0}.|{0} için checksum eksik.|Відсутня контрольна сума для {0}.|Отсутствует checksum для {0}.|مجموع التحقق مفقود لـ {0}.|Λείπει checksum για το {0}.|Lipsește checksum pentru {0}.|{0} のチェックサムがありません。|{0}의 체크섬이 없습니다.|缺少 {0} 的校验和。|缺少 {0} 的校驗碼。",
        "Engine.HashFailedFile|Checksum verification failed for {0}.|אימות checksum נכשל עבור {0}.|Falló la verificación del checksum de {0}.|Échec de vérification du checksum de {0}.|Checksum-Prüfung für {0} fehlgeschlagen.|Verifica checksum fallita per {0}.|Falha na verificação do checksum de {0}.|Checksumcontrole mislukt voor {0}.|Weryfikacja sumy kontrolnej dla {0} nie powiodła się.|Ověření kontrolního součtu pro {0} selhalo.|{0} checksum doğrulaması başarısız.|Перевірка контрольної суми для {0} не вдалася.|Проверка checksum для {0} не удалась.|فشل التحقق من checksum لـ {0}.|Η επαλήθευση checksum για το {0} απέτυχε.|Verificarea checksum pentru {0} a eșuat.|{0} のチェックサム検証に失敗しました。|{0} 체크섬 검증 실패.|{0} 校验和验证失败。|{0} 校驗碼驗證失敗。",
        "Engine.FfmpegMissingExecutables|FFmpeg package is missing ffmpeg.exe or ffprobe.exe.|בחבילת FFmpeg חסרים ffmpeg.exe או ffprobe.exe.|El paquete FFmpeg no contiene ffmpeg.exe o ffprobe.exe.|Le paquet FFmpeg ne contient pas ffmpeg.exe ou ffprobe.exe.|Im FFmpeg-Paket fehlt ffmpeg.exe oder ffprobe.exe.|Il pacchetto FFmpeg non contiene ffmpeg.exe o ffprobe.exe.|O pacote FFmpeg não contém ffmpeg.exe ou ffprobe.exe.|Het FFmpeg-pakket mist ffmpeg.exe of ffprobe.exe.|Pakiet FFmpeg nie zawiera ffmpeg.exe lub ffprobe.exe.|Balíček FFmpeg neobsahuje ffmpeg.exe nebo ffprobe.exe.|FFmpeg paketinde ffmpeg.exe veya ffprobe.exe eksik.|Пакет FFmpeg не містить ffmpeg.exe або ffprobe.exe.|Пакет FFmpeg не содержит ffmpeg.exe или ffprobe.exe.|حزمة FFmpeg تفتقد ffmpeg.exe أو ffprobe.exe.|Το πακέτο FFmpeg δεν περιέχει ffmpeg.exe ή ffprobe.exe.|Pachetul FFmpeg nu conține ffmpeg.exe sau ffprobe.exe.|FFmpegパッケージにffmpeg.exeまたはffprobe.exeがありません。|FFmpeg 패키지에 ffmpeg.exe 또는 ffprobe.exe가 없습니다.|FFmpeg 包中缺少 ffmpeg.exe 或 ffprobe.exe。|FFmpeg 套件缺少 ffmpeg.exe 或 ffprobe.exe。",
        "Engine.HashMissingFfmpeg|FFmpeg checksum is missing.|חסר checksum ל־FFmpeg.|Falta el checksum de FFmpeg.|Le checksum de FFmpeg manque.|FFmpeg-Checksum fehlt.|Checksum FFmpeg mancante.|O checksum do FFmpeg está ausente.|FFmpeg checksum ontbreekt.|Brak sumy kontrolnej FFmpeg.|Chybí checksum FFmpeg.|FFmpeg checksum eksik.|Відсутня контрольна сума FFmpeg.|Отсутствует checksum FFmpeg.|مجموع التحقق لـFFmpeg مفقود.|Λείπει checksum του FFmpeg.|Lipsește checksum pentru FFmpeg.|FFmpegのチェックサムがありません。|FFmpeg 체크섬이 없습니다.|缺少 FFmpeg 校验和。|缺少 FFmpeg 校驗碼。",
        "Engine.HashFailedFfmpeg|FFmpeg checksum verification failed.|אימות checksum של FFmpeg נכשל.|Falló la verificación del checksum de FFmpeg.|Échec de vérification du checksum de FFmpeg.|FFmpeg-Checksum-Prüfung fehlgeschlagen.|Verifica checksum FFmpeg fallita.|Falha na verificação do checksum do FFmpeg.|FFmpeg checksumcontrole mislukt.|Weryfikacja sumy kontrolnej FFmpeg nie powiodła się.|Ověření checksum FFmpeg selhalo.|FFmpeg checksum doğrulaması başarısız.|Перевірка контрольної суми FFmpeg не вдалася.|Проверка checksum FFmpeg не удалась.|فشل التحقق من checksum لـFFmpeg.|Αποτυχία επαλήθευσης checksum FFmpeg.|Verificarea checksum FFmpeg a eșuat.|FFmpegのチェックサム検証に失敗しました。|FFmpeg 체크섬 검증 실패.|FFmpeg 校验和验证失败。|FFmpeg 校驗碼驗證失敗。",
        "Engine.HashMissingDeno|Deno checksum is missing.|חסר checksum ל־Deno.|Falta el checksum de Deno.|Le checksum de Deno manque.|Deno-Checksum fehlt.|Checksum Deno mancante.|O checksum do Deno está ausente.|Deno checksum ontbreekt.|Brak sumy kontrolnej Deno.|Chybí checksum Deno.|Deno checksum eksik.|Відсутня контрольна сума Deno.|Отсутствует checksum Deno.|مجموع التحقق لـDeno مفقود.|Λείπει checksum του Deno.|Lipsește checksum pentru Deno.|Denoのチェックサムがありません。|Deno 체크섬이 없습니다.|缺少 Deno 校验和。|缺少 Deno 校驗碼。",
        "Engine.HashFailedDeno|Deno checksum verification failed.|אימות checksum של Deno נכשל.|Falló la verificación del checksum de Deno.|Échec de vérification du checksum de Deno.|Deno-Checksum-Prüfung fehlgeschlagen.|Verifica checksum Deno fallita.|Falha na verificação do checksum do Deno.|Deno checksumcontrole mislukt.|Weryfikacja sumy kontrolnej Deno nie powiodła się.|Ověření checksum Deno selhalo.|Deno checksum doğrulaması başarısız.|Перевірка контрольної суми Deno не вдалася.|Проверка checksum Deno не удалась.|فشل التحقق من checksum لـDeno.|Αποτυχία επαλήθευσης checksum Deno.|Verificarea checksum Deno a eșuat.|Denoのチェックサム検証に失敗しました。|Deno 체크섬 검증 실패.|Deno 校验和验证失败。|Deno 校驗碼驗證失敗。",
        "Engine.DenoMissingExecutable|Deno package is missing deno.exe.|בחבילת Deno חסר deno.exe.|El paquete Deno no contiene deno.exe.|Le paquet Deno ne contient pas deno.exe.|Im Deno-Paket fehlt deno.exe.|Il pacchetto Deno non contiene deno.exe.|O pacote Deno não contém deno.exe.|Het Deno-pakket mist deno.exe.|Pakiet Deno nie zawiera deno.exe.|Balíček Deno neobsahuje deno.exe.|Deno paketinde deno.exe eksik.|Пакет Deno не містить deno.exe.|Пакет Deno не содержит deno.exe.|حزمة Deno تفتقد deno.exe.|Το πακέτο Deno δεν περιέχει deno.exe.|Pachetul Deno nu conține deno.exe.|Denoパッケージにdeno.exeがありません。|Deno 패키지에 deno.exe가 없습니다.|Deno 包中缺少 deno.exe。|Deno 套件缺少 deno.exe。",

        "Error.MetadataMissing|The media information could not be read.|לא ניתן היה לקרוא את פרטי המדיה.|No se pudo leer la información multimedia.|Impossible de lire les informations du média.|Die Medieninformationen konnten nicht gelesen werden.|Impossibile leggere le informazioni multimediali.|Não foi possível ler as informações de mídia.|Media-informatie kon niet worden gelezen.|Nie można odczytać informacji o multimediach.|Nepodařilo se načíst informace o médiu.|Medya bilgileri okunamadı.|Не вдалося прочитати інформацію про медіа.|Не удалось прочитать информацию о медиа.|تعذر قراءة معلومات الوسائط.|Δεν ήταν δυνατή η ανάγνωση των πληροφοριών πολυμέσων.|Nu s-au putut citi informațiile media.|メディア情報を読み取れませんでした。|미디어 정보를 읽을 수 없습니다.|无法读取媒体信息。|無法讀取媒體資訊。",
        "Error.DownloadedFileEmpty|The downloaded file is empty.|הקובץ שהורד ריק.|El archivo descargado está vacío.|Le fichier téléchargé est vide.|Die heruntergeladene Datei ist leer.|Il file scaricato è vuoto.|O arquivo baixado está vazio.|Het gedownloade bestand is leeg.|Pobrany plik jest pusty.|Stažený soubor je prázdný.|İndirilen dosya boş.|Завантажений файл порожній.|Загруженный файл пуст.|الملف الذي تم تنزيله فارغ.|Το ληφθέν αρχείο είναι κενό.|Fișierul descărcat este gol.|ダウンロードしたファイルは空です。|다운로드한 파일이 비어 있습니다.|下载的文件为空。|下載的檔案是空的。",

        "Explorer.AllSaved|All changes are saved.|כל השינויים נשמרו.|Todos los cambios están guardados.|Toutes les modifications sont enregistrées.|Alle Änderungen sind gespeichert.|Tutte le modifiche sono salvate.|Todas as alterações foram salvas.|Alle wijzigingen zijn opgeslagen.|Wszystkie zmiany zapisane.|Všechny změny jsou uloženy.|Tüm değişiklikler kaydedildi.|Усі зміни збережено.|Все изменения сохранены.|تم حفظ كل التغييرات.|Όλες οι αλλαγές αποθηκεύτηκαν.|Toate modificările sunt salvate.|すべての変更を保存しました。|모든 변경 사항이 저장되었습니다.|所有更改已保存。|所有變更已儲存。",
        "Explorer.SomeNeedAttention|Some changes need attention.|חלק מהשינויים דורשים תשומת לב.|Algunos cambios requieren atención.|Certaines modifications nécessitent votre attention.|Einige Änderungen benötigen Aufmerksamkeit.|Alcune modifiche richiedono attenzione.|Algumas alterações precisam de atenção.|Sommige wijzigingen vereisen aandacht.|Niektóre zmiany wymagają uwagi.|Některé změny vyžadují pozornost.|Bazı değişiklikler dikkat gerektiriyor.|Деякі зміни потребують уваги.|Некоторые изменения требуют внимания.|بعض التغييرات تحتاج إلى انتباه.|Ορισμένες αλλαγές χρειάζονται προσοχή.|Unele modificări necesită atenție.|一部の変更に注意が必要です。|일부 변경 사항을 확인해야 합니다.|某些更改需要处理。|某些變更需要注意。",
        "Explorer.ApplyingChanges|Applying staged changes…|מחיל את השינויים הממתינים…|Aplicando cambios pendientes…|Application des modifications en attente…|Vorgemerkte Änderungen werden angewendet…|Applicazione delle modifiche in sospeso…|Aplicando alterações pendentes…|Wachtende wijzigingen toepassen…|Stosowanie oczekujących zmian…|Používání čekajících změn…|Bekleyen değişiklikler uygulanıyor…|Застосування очікуваних змін…|Применение ожидающих изменений…|تطبيق التغييرات المعلقة…|Εφαρμογή εκκρεμών αλλαγών…|Se aplică modificările în așteptare…|保留中の変更を適用しています…|대기 변경 사항을 적용하는 중…|正在应用待处理更改…|正在套用待處理變更…",
        "Explorer.Cancelled|Cancelled: {0}|בוטל: {0}|Cancelado: {0}|Annulé : {0}|Abgebrochen: {0}|Annullato: {0}|Cancelado: {0}|Geannuleerd: {0}|Anulowano: {0}|Zrušeno: {0}|İptal edildi: {0}|Скасовано: {0}|Отменено: {0}|تم الإلغاء: {0}|Ακυρώθηκε: {0}|Anulat: {0}|キャンセル: {0}|취소됨: {0}|已取消：{0}|已取消：{0}",
        "Explorer.MediaAddedOne|Media added to the pending queue.|המדיה נוספה לתור השינויים הממתינים.|El medio se añadió a la cola pendiente.|Le média a été ajouté à la file d’attente.|Medium wurde vorgemerkt.|Il media è stato aggiunto alla coda.|A mídia foi adicionada à fila.|Media is aan de wachtrij toegevoegd.|Multimedia dodano do kolejki.|Médium bylo přidáno do fronty.|Medya bekleyen kuyruğa eklendi.|Медіа додано до черги.|Медиа добавлено в очередь.|تمت إضافة الوسائط إلى قائمة الانتظار.|Το πολυμέσο προστέθηκε στην ουρά.|Media a fost adăugată în coadă.|メディアを保留キューに追加しました。|미디어가 대기열에 추가되었습니다.|媒体已加入待处理队列。|媒體已加入待處理佇列。",
        "Explorer.MediaAddedMany|{0} media items added to the pending queue.|{0} פריטי מדיה נוספו לתור השינויים הממתינים.|Se añadieron {0} elementos multimedia a la cola pendiente.|{0} médias ajoutés à la file d’attente.|{0} Medien wurden vorgemerkt.|{0} elementi multimediali aggiunti alla coda.|{0} itens de mídia adicionados à fila.|{0} media-items aan de wachtrij toegevoegd.|Dodano {0} elementów multimedialnych do kolejki.|Do fronty přidány {0} položky médií.|{0} medya öğesi bekleyen kuyruğa eklendi.|{0} елементів медіа додано до черги.|В очередь добавлено {0} медиа.|تمت إضافة {0} عناصر وسائط إلى قائمة الانتظار.|{0} στοιχεία πολυμέσων προστέθηκαν στην ουρά.|{0} elemente media adăugate în coadă.|{0} 件のメディアを保留キューに追加しました。|미디어 {0}개가 대기열에 추가되었습니다.|已将 {0} 个媒体项目加入待处理队列。|已將 {0} 個媒體項目加入待處理佇列。",
        "Explorer.PendingCreate|Pending: create “{0}”.|ממתין: יצירת „{0}“.|Pendiente: crear “{0}”.|En attente : créer « {0} ».|Ausstehend: „{0}“ erstellen.|In sospeso: crea “{0}”.|Pendente: criar “{0}”.|In afwachting: “{0}” maken.|Oczekuje: utworzenie „{0}”.|Čeká se: vytvořit „{0}“.|Bekliyor: “{0}” oluştur.|В очікуванні: створити «{0}».|Ожидается: создать «{0}».|معلق: إنشاء «{0}».|Σε αναμονή: δημιουργία «{0}».|În așteptare: creează „{0}”.|保留中: 「{0}」を作成します。|대기: “{0}” 만들기.|待处理：创建“{0}”。|待處理：建立「{0}」。",
        "Explorer.PendingRename|Pending: rename “{0}”.|ממתין: שינוי השם של „{0}“.|Pendiente: cambiar el nombre de “{0}”.|En attente : renommer « {0} ».|Ausstehend: „{0}“ umbenennen.|In sospeso: rinomina “{0}”.|Pendente: renomear “{0}”.|In afwachting: “{0}” hernoemen.|Oczekuje: zmiana nazwy „{0}”.|Čeká se: přejmenovat „{0}“.|Bekliyor: “{0}” yeniden adlandır.|В очікуванні: перейменувати «{0}».|Ожидается: переименовать «{0}».|معلق: إعادة تسمية «{0}».|Σε αναμονή: μετονομασία «{0}».|În așteptare: redenumește „{0}”.|保留中: 「{0}」の名前を変更します。|대기: “{0}” 이름 바꾸기.|待处理：重命名“{0}”。|待處理：重新命名「{0}」。",
        "Explorer.PendingDelete|Pending: delete “{0}”.|ממתין: מחיקת „{0}“.|Pendiente: eliminar “{0}”.|En attente : supprimer « {0} ».|Ausstehend: „{0}“ löschen.|In sospeso: elimina “{0}”.|Pendente: excluir “{0}”.|In afwachting: “{0}” verwijderen.|Oczekuje: usunięcie „{0}”.|Čeká se: odstranit „{0}“.|Bekliyor: “{0}” sil.|В очікуванні: видалити «{0}».|Ожидается: удалить «{0}».|معلق: حذف «{0}».|Σε αναμονή: διαγραφή «{0}».|În așteptare: șterge „{0}”.|保留中: 「{0}」を削除します。|대기: “{0}” 삭제.|待处理：删除“{0}”。|待處理：刪除「{0}」。",
        "Explorer.NewFolder|New folder|תיקייה חדשה|Nueva carpeta|Nouveau dossier|Neuer Ordner|Nuova cartella|Nova pasta|Nieuwe map|Nowy folder|Nová složka|Yeni klasör|Нова папка|Новая папка|مجلد جديد|Νέος φάκελος|Folder nou|新しいフォルダー|새 폴더|新建文件夹|新增資料夾",
        "Explorer.NewFolderPrompt|Choose a name for the new folder.|בחר שם לתיקייה החדשה.|Elige un nombre para la nueva carpeta.|Choisissez un nom pour le nouveau dossier.|Wähle einen Namen für den neuen Ordner.|Scegli un nome per la nuova cartella.|Escolha um nome para a nova pasta.|Kies een naam voor de nieuwe map.|Wybierz nazwę nowego folderu.|Zvolte název nové složky.|Yeni klasör için bir ad seçin.|Виберіть назву нової папки.|Выберите имя новой папки.|اختر اسمًا للمجلد الجديد.|Επιλέξτε όνομα για τον νέο φάκελο.|Alege un nume pentru folderul nou.|新しいフォルダー名を入力してください。|새 폴더 이름을 선택하세요.|选择新文件夹的名称。|選擇新資料夾的名稱。",
        "Explorer.NewFolderDefault|New Folder|תיקייה חדשה|Nueva carpeta|Nouveau dossier|Neuer Ordner|Nuova cartella|Nova pasta|Nieuwe map|Nowy folder|Nová složka|Yeni Klasör|Нова папка|Новая папка|مجلد جديد|Νέος φάκελος|Folder nou|新しいフォルダー|새 폴더|新建文件夹|新增資料夾",
        "Explorer.RenamePrompt|Enter the new name.|הזן את השם החדש.|Escribe el nuevo nombre.|Entrez le nouveau nom.|Gib den neuen Namen ein.|Inserisci il nuovo nome.|Digite o novo nome.|Voer de nieuwe naam in.|Wpisz nową nazwę.|Zadejte nový název.|Yeni adı girin.|Введіть нову назву.|Введите новое имя.|أدخل الاسم الجديد.|Εισαγάγετε το νέο όνομα.|Introdu noul nume.|新しい名前を入力してください。|새 이름을 입력하세요.|输入新名称。|輸入新名稱。",
        "Explorer.DeleteFolderPrompt|Delete folder “{0}” from the staged plan?|למחוק את התיקייה „{0}“ מתוכנית השינויים?|¿Eliminar la carpeta “{0}” del plan pendiente?|Supprimer le dossier « {0} » du plan en attente ?|Ordner „{0}“ aus dem vorgemerkten Plan löschen?|Eliminare la cartella “{0}” dal piano in sospeso?|Excluir a pasta “{0}” do plano pendente?|Map “{0}” uit het wachtende plan verwijderen?|Usunąć folder „{0}” z oczekujących zmian?|Odstranit složku „{0}“ z čekajících změn?|“{0}” klasörü bekleyen plandan silinsin mi?|Видалити папку «{0}» з очікуваних змін?|Удалить папку «{0}» из списка ожидающих изменений?|حذف المجلد «{0}» من الخطة المعلقة؟|Διαγραφή του φακέλου «{0}» από το σχέδιο σε αναμονή;|Ștergi folderul „{0}” din planul în așteptare?|保留プランから「{0}」を削除しますか？|“{0}” 폴더를 대기 계획에서 삭제할까요?|要从待处理计划中删除文件夹“{0}”吗？|要從待處理計畫中刪除資料夾「{0}」嗎？",
        "Explorer.DeleteFilePrompt|Delete “{0}” from the staged plan?|למחוק את „{0}“ מתוכנית השינויים?|¿Eliminar “{0}” del plan pendiente?|Supprimer « {0} » du plan en attente ?|„{0}“ aus dem vorgemerkten Plan löschen?|Eliminare “{0}” dal piano in sospeso?|Excluir “{0}” do plano pendente?|“{0}” uit het wachtende plan verwijderen?|Usunąć „{0}” z oczekujących zmian?|Odstranit „{0}“ z čekajících změn?|“{0}” bekleyen plandan silinsin mi?|Видалити «{0}» з очікуваних змін?|Удалить «{0}» из списка ожидающих изменений?|حذف «{0}» من الخطة المعلقة؟|Διαγραφή «{0}» από το σχέδιο σε αναμονή;|Ștergi „{0}” din planul în așteptare?|保留プランから「{0}」を削除しますか？|“{0}”을 대기 계획에서 삭제할까요?|要从待处理计划中删除“{0}”吗？|要從待處理計畫中刪除「{0}」嗎？",
        "Explorer.ConfirmDelete|Confirm delete|אישור מחיקה|Confirmar eliminación|Confirmer la suppression|Löschen bestätigen|Conferma eliminazione|Confirmar exclusão|Verwijderen bevestigen|Potwierdź usunięcie|Potvrdit odstranění|Silmeyi onayla|Підтвердити видалення|Подтвердить удаление|تأكيد الحذف|Επιβεβαίωση διαγραφής|Confirmă ștergerea|削除を確認|삭제 확인|确认删除|確認刪除",
        "Explorer.SaveChangesArrow|Save changes  →|שמור שינויים  ←|Guardar cambios  →|Enregistrer les modifications  →|Änderungen speichern  →|Salva modifiche  →|Salvar alterações  →|Wijzigingen opslaan  →|Zapisz zmiany  →|Uložit změny  →|Değişiklikleri kaydet  →|Зберегти зміни  →|Сохранить изменения  →|حفظ التغييرات  ←|Αποθήκευση αλλαγών  →|Salvează modificările  →|変更を保存  →|변경 사항 저장  →|保存更改  →|儲存變更  →",
        "Explorer.SaveChangesCount|Save changes ({0})  →|שמור שינויים ({0})  ←|Guardar cambios ({0})  →|Enregistrer les modifications ({0})  →|Änderungen speichern ({0})  →|Salva modifiche ({0})  →|Salvar alterações ({0})  →|Wijzigingen opslaan ({0})  →|Zapisz zmiany ({0})  →|Uložit změny ({0})  →|Değişiklikleri kaydet ({0})  →|Зберегти зміни ({0})  →|Сохранить изменения ({0})  →|حفظ التغييرات ({0})  ←|Αποθήκευση αλλαγών ({0})  →|Salvează modificările ({0})  →|変更を保存 ({0})  →|변경 사항 저장 ({0})  →|保存更改 ({0})  →|儲存變更 ({0})  →",
        "Explorer.QueuedOne|1 queued|1 בתור|1 en cola|1 en attente|1 in der Warteschlange|1 in coda|1 na fila|1 in wachtrij|1 w kolejce|1 ve frontě|1 kuyrukta|1 у черзі|1 в очереди|1 في الانتظار|1 σε ουρά|1 în coadă|1件待機中|1개 대기|1 个待处理|1 個待處理",
        "Explorer.Queued|{0} queued|{0} בתור|{0} en cola|{0} en attente|{0} in der Warteschlange|{0} in coda|{0} na fila|{0} in wachtrij|{0} w kolejce|{0} ve frontě|{0} kuyrukta|{0} у черзі|{0} в очереди|{0} في الانتظار|{0} σε ουρά|{0} în coadă|{0}件待機中|{0}개 대기|{0} 个待处理|{0} 個待處理",

        "AddMedia.PastePrompt|Paste a YouTube video or playlist URL.|הדבק קישור לסרטון או פלייליסט של YouTube.|Pega la URL de un vídeo o playlist de YouTube.|Collez l’URL d’une vidéo ou playlist YouTube.|YouTube-Video- oder Playlist-URL einfügen.|Incolla l’URL di un video o playlist YouTube.|Cole o URL de um vídeo ou playlist do YouTube.|Plak een YouTube-video- of playlist-URL.|Wklej adres URL filmu lub playlisty YouTube.|Vložte URL videa nebo playlistu YouTube.|YouTube video veya oynatma listesi URL'si yapıştırın.|Вставте URL відео або плейлиста YouTube.|Вставьте URL видео или плейлиста YouTube.|ألصق رابط فيديو أو قائمة تشغيل على YouTube.|Επικολλήστε URL βίντεο ή playlist YouTube.|Lipește URL-ul unui videoclip sau playlist YouTube.|YouTube動画またはプレイリストのURLを貼り付けてください。|YouTube 동영상 또는 재생목록 URL을 붙여 넣으세요.|粘贴 YouTube 视频或播放列表 URL。|貼上 YouTube 影片或播放清單 URL。",
        "AddMedia.NothingFound|Nothing was found. Check the link and try again.|לא נמצא דבר. בדוק את הקישור ונסה שוב.|No se encontró nada. Comprueba el enlace e inténtalo de nuevo.|Aucun élément trouvé. Vérifiez le lien et réessayez.|Nichts gefunden. Prüfe den Link und versuche es erneut.|Non è stato trovato nulla. Controlla il link e riprova.|Nada foi encontrado. Verifique o link e tente novamente.|Niets gevonden. Controleer de link en probeer opnieuw.|Nic nie znaleziono. Sprawdź link i spróbuj ponownie.|Nic nenalezeno. Zkontrolujte odkaz a zkuste to znovu.|Bir şey bulunamadı. Bağlantıyı kontrol edip tekrar deneyin.|Нічого не знайдено. Перевірте посилання та спробуйте ще раз.|Ничего не найдено. Проверьте ссылку и попробуйте снова.|لم يتم العثور على شيء. تحقق من الرابط وحاول مرة أخرى.|Δεν βρέθηκε τίποτα. Ελέγξτε τον σύνδεσμο και δοκιμάστε ξανά.|Nu s-a găsit nimic. Verifică linkul și încearcă din nou.|何も見つかりませんでした。リンクを確認してもう一度お試しください。|항목을 찾지 못했습니다. 링크를 확인하고 다시 시도하세요.|未找到任何内容。检查链接后重试。|找不到任何內容。請檢查連結後再試。",
        "AddMedia.OneReady|1 media item ready. Edit the options before adding.|פריט מדיה אחד מוכן. ערוך את האפשרויות לפני ההוספה.|1 elemento multimedia listo. Edita las opciones antes de añadirlo.|1 média prêt. Modifiez les options avant de l’ajouter.|1 Medienelement bereit. Optionen vor dem Hinzufügen bearbeiten.|1 elemento multimediale pronto. Modifica le opzioni prima di aggiungerlo.|1 item de mídia pronto. Edite as opções antes de adicionar.|1 media-item klaar. Pas de opties aan.|1 element gotowy. Zmień opcje przed dodaniem.|1 položka média připravena. Před přidáním upravte možnosti.|1 medya öğesi hazır. Eklemeye başlamadan seçenekleri düzenleyin.|1 медіа готове. Налаштуйте параметри перед додаванням.|1 медиа готово. Измените параметры перед добавлением.|عنصر وسائط واحد جاهز. عدّل الخيارات قبل الإضافة.|1 στοιχείο πολυμέσων έτοιμο. Επεξεργαστείτε τις επιλογές πριν την προσθήκη.|1 element media pregătit. Editează opțiunile înainte de adăugare.|1件のメディアが準備できました。追加前にオプションを編集してください。|미디어 1개가 준비되었습니다. 추가하기 전에 옵션을 편집하세요.|1 个媒体项目已准备就绪。添加前请编辑选项。|1 個媒體項目已準備就緒。新增前請編輯選項。",
        "AddMedia.ManyReady|{0} media items ready. Each row is independent.|{0} פריטי מדיה מוכנים. כל שורה עצמאית.|{0} elementos multimedia listos. Cada fila es independiente.|{0} médias prêts. Chaque ligne est indépendante.|{0} Medienelemente bereit. Jede Zeile ist unabhängig.|{0} elementi multimediali pronti. Ogni riga è indipendente.|{0} itens de mídia prontos. Cada linha é independente.|{0} media-items klaar. Elke rij is onafhankelijk.|{0} elementów multimedialnych gotowych. Każdy wiersz jest niezależny.|{0} položek média připraveno. Každý řádek je samostatný.|{0} medya öğesi hazır. Her satır bağımsızdır.|{0} елементів медіа готові. Кожен рядок незалежний.|{0} медиа готовы. Каждая строка независима.|{0} عناصر وسائط جاهزة. كل سطر مستقل.|{0} στοιχεία πολυμέσων έτοιμα. Κάθε γραμμή είναι ανεξάρτητη.|{0} elemente media pregătite. Fiecare rând este independent.|{0}件のメディアが準備できました。各行は独立しています。|미디어 {0}개가 준비되었습니다. 각 행은 독립적입니다.|{0} 个媒体项目已准备就绪。每行独立。|{0} 個媒體項目已準備就緒。每列獨立。",
        "AddMedia.AnalysisCancelled|Analysis cancelled.|הניתוח בוטל.|Análisis cancelado.|Analyse annulée.|Analyse abgebrochen.|Analisi annullata.|Análise cancelada.|Analyse geannuleerd.|Analiza anulowana.|Analýza zrušena.|Analiz iptal edildi.|Аналіз скасовано.|Анализ отменён.|تم إلغاء التحليل.|Η ανάλυση ακυρώθηκε.|Analiză anulată.|解析をキャンセルしました。|분석이 취소되었습니다.|分析已取消。|分析已取消。",
        "AddMedia.ErrorFallback|We couldn't analyze this link. Please try again.|לא ניתן היה לנתח את הקישור. נסה שוב.|No se pudo analizar el enlace. Inténtalo de nuevo.|Impossible d’analyser ce lien. Réessayez.|Dieser Link konnte nicht analysiert werden. Bitte erneut versuchen.|Impossibile analizzare questo link. Riprova.|Não foi possível analisar este link. Tente novamente.|Deze link kon niet worden geanalyseerd. Probeer opnieuw.|Nie można przeanalizować tego linku. Spróbuj ponownie.|Odkaz se nepodařilo analyzovat. Zkuste to znovu.|Bu bağlantı analiz edilemedi. Tekrar deneyin.|Не вдалося проаналізувати це посилання. Спробуйте ще раз.|Не удалось проанализировать ссылку. Попробуйте снова.|تعذر تحليل الرابط. حاول مرة أخرى.|Δεν ήταν δυνατή η ανάλυση του συνδέσμου. Δοκιμάστε ξανά.|Nu s-a putut analiza linkul. Încearcă din nou.|このリンクを解析できませんでした。もう一度お試しください。|이 링크를 분석할 수 없습니다. 다시 시도하세요.|无法分析此链接。请重试。|無法分析此連結。請再試一次。",
        "Media.Source|Source|מקור|Origen|Source|Quelle|Sorgente|Origem|Bron|Źródło|Zdroj|Kaynak|Джерело|Источник|المصدر|Πηγή|Sursă|ソース|소스|来源|來源",

        "Common.Cancel|Cancel|ביטול|Cancelar|Annuler|Abbrechen|Annulla|Cancelar|Annuleren|Anuluj|Zrušit|İptal|Скасувати|Отмена|إلغاء|Ακύρωση|Anulează|キャンセル|취소|取消|取消",
        "Common.Continue|Continue|המשך|Continuar|Continuer|Weiter|Continua|Continuar|Doorgaan|Kontynuuj|Pokračovat|Devam|Продовжити|Продолжить|متابعة|Συνέχεια|Continuă|続行|계속|继续|繼續",
        "Common.Delete|Delete|מחק|Eliminar|Supprimer|Löschen|Elimina|Excluir|Verwijderen|Usuń|Odstranit|Sil|Видалити|Удалить|حذف|Διαγραφή|Șterge|削除|삭제|删除|刪除"
    ];

    public static void Apply(IDictionary<string, Dictionary<string, string>> dictionaries)
    {
        for (var languageIndex = 0; languageIndex < Languages.Length; languageIndex++)
        {
            if (!dictionaries.TryGetValue(Languages[languageIndex], out var dictionary))
                dictionary = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            foreach (var row in Rows)
            {
                var parts = row.Split('|');
                if (parts.Length <= languageIndex + 1)
                    continue;

                dictionary[parts[0]] = parts[languageIndex + 1];
            }

            dictionaries[Languages[languageIndex]] = dictionary;
        }
    }
}
